src/ast.rkt, src/component.rkt
The [threading](https://docs.racket-lang.org/threading/index.html?q=threading) library makes some of the nasty function calls nicer. Take a look if you have time!
=> rewrite function nests with threading

src/vizualizer.rkt
use send* instead of send for multiple calls to the same object
=> Minor fixes to class syntax

calyx/src/ast.rs, calyx/src/main.rs, calyx/src/parse.rs, calyx/src/pass.rs, calyx/src/unit_pass.rs
@kwf37 Let me know what you think of this. I think this seems like the way to go, it gives the type system a little more information.
=> Better visitor

calyx/src/ast.rs, calyx/src/main.rs, calyx/src/pretty_print.rs, calyx/src/rtl_gen.rs, calyx/src/utils.rs
Check it out. I think there's an easy way to add indentation without too many changes so I'm gonna spend a half hour on it real quick.
=> Finished basic pretty-printer. Need to fix indentation

calyx/examples/ifseq.futil, calyx/examples/par.futil, calyx/examples/while-seq.futil, calyx/primitives/std.lib, calyx/src/errors.rs
Update the examples so that they parse and compile with the current compiler. This fixes issue #62.
=> fix examples

calyx/src/main.rs, calyx/src/passes/collapse_seq.rs, calyx/src/passes/mod.rs
Implement sequence collapsing #74
=> Collapse seq

calyx/Cargo.toml, calyx/src/cmdline.rs, calyx/src/lang/ast.rs, calyx/src/lang/context.rs, runt.toml, tests/automatic-par/basic.futil, tests/automatic-par/common_comp.futil, tests/automatic-par/interspersed_stmt.futil, tests/automatic-par/parseq.futil, tests/automatic-par/parseq2.futil, tests/collapse-seq/collapse-with-par.futil, tests/collapse-seq/nested-seq.futil, tests/collapse-seq/should-collapse.futil, tests/integration/counter.futil, tests/integration/fib.futil, tests/integration/ifseq.futil, tests/integration/par.futil, tests/integration/seq.futil, tests/integration/simple.futil, tests/integration/while-seq.futil, tests/latency-insensitive/adds-ready-valid-ports.futil
implements issue #114 
* Libraries can be defined in futil files
* -library flag now defines the directory to look for library files
* The parser is still being worked on to make import statement optional
=> Define library

README.md
Just a few things I noticed while following the README to try and run a few Dahlia programs. It works!!!!!!!!
=> Couple o' README improvements

.github/workflows/rust.yml
https://capra.cs.cornell.edu/calyx
=> Documentation autobuild

docs/SUMMARY.md, docs/optimizations/dataflow.md, docs/optimizations/index.md
a write up on how to think about dataflow analyses in FuTIL. Some things can be clarified I think, but I'm calling it good for now.
=> Opt writeup

calyx/src/frontend/futil_syntax.pest, calyx/src/frontend/parser.rs, runt.toml, tests/errors/parser/cell-missing-semi.expect, tests/errors/parser/cell-missing-semi.futil, tests/errors/parser/num-without-bitwidth.expect, tests/errors/parser/num-without-bitwidth.futil, tests/errors/parser/while-without-body.expect, tests/errors/parser/while-without-body.futil, tests/errors/parser/wrong-binary-num.expect, tests/errors/parser/wrong-binary-num.futil
=> Parser fixes

primitives/std.lib
It initially wouldn't lower. It now does.
=> Fix std_smult_pipe.

calyx/src/backend/verilog.rs
=> Use assign instead of always_comb

frontends/systolic-lang/gen-systolic.py, fud/fud/config.py, fud/fud/errors.py, fud/fud/exec.py, fud/fud/registry.py, fud/fud/stages/__init__.py, fud/fud/stages/systolic.py, fud/fud/vivado/extract.py, fud/fud/vivado/rpt.py
- Allow systolic frontend to take a single json file as input with size specifications
- add fud interface for dynamically choosing a command to run based on context
- increased the resources that we record
=> Fud niceties

fud/fud/stages/verilator.py, runt.toml
=> made dat stage report cycles

frontends/ntt-pipeline/gen-ntt-pipeline.py, tests/frontend/ntt-pipeline/ntt-4.expect
=> Reduce `mult_pipe`s in NTT from N to N/2.

docs/SUMMARY.md, docs/frontends/systolic-array.md, docs/frontends/tvm-relay.md, docs/intro.md
Updates and places Relay docs in the book.
=> [Relay] docs

examples/README.md
Changed it to a working command, the previous resulted in error due to syntax
=> Update Calyx simulation example

frontends/ntt-pipeline/gen-ntt-pipeline.py, primitives/bitnum/unsigned.futil, primitives/bitnum/unsigned.sv, tests/frontend/ntt-pipeline/ntt-4.expect
=> Unify mod and div implemetations

docs/contributors.md
=> [Docs] Contributors update

calyx-py/futil/ast.py, primitives/fixed/signed.futil, primitives/fixed/signed.sv, primitives/fixed/unsigned.futil, primitives/fixed/unsigned.sv, tests/correctness/numeric-types/fixed-point/binary-operators.futil, tests/correctness/numeric-types/fixed-point/different-widths.futil, tests/frontend/dahlia/fixed-point-add.expect, tests/frontend/dahlia/fixed-point-different-widths.expect, tests/frontend/dahlia/matadd-fixed-point.expect, tests/frontend/relay/bias_add.expect, tests/frontend/relay/relu.expect
Step before adding any new primitives.
Accompanying [Dahlia #365](https://github.com/cucapra/dahlia/pull/365)
=> Rename fixed point primitives to `std_fp_{}`.

.github/workflows/integration.yml
=> Use polybench benchmarks for integration testing

docs/SUMMARY.md, docs/interpreter.md, interp/src/main.rs
Fixes #565.
Hit the green button if LGTM.
=> Remove unused interpter CLI options and add docs

calyx/src/backend/xilinx/axi.rs, calyx/src/backend/xilinx/axi_address_space.rs, calyx/src/backend/xilinx/control_axi.rs, calyx/src/backend/xilinx/fsm.rs, calyx/src/backend/xilinx/memory_axi.rs, calyx/src/backend/xilinx/mod.rs, calyx/src/backend/xilinx/toplevel.rs, calyx/src/backend/xilinx/xml.rs, calyx/src/passes/reset_insertion.rs, calyx/src/passes/synthesis_papercut.rs, fud/bitstream/sim_script.tcl, fud/fud/config.py, src/cmdline.rs, tests/errors/mem-only-reads.expect
Final slice of #571. Implements resetting logic for Xilinx FPGAs.
Closes #571. Closes #529.
=> Resetting logic for our Xilinx FPGAs

calyx/src/default_passes.rs, calyx/src/pass_manager.rs
Steals this idea from how MLIR registers its dialects.
=> Pass manager trait-based method to register passes.

calyx/src/ir/attribute.rs, src/backend/circt.rs, tests/backend/circt/attributes.expect, tests/backend/circt/attributes.futil, tests/backend/circt/no-guards.expect, tests/backend/circt/with-guards.expect
- [CIRCT] newline after calyx.program
- [CIRCT] Generate attributes. Fixes #659.
=> [CIRCT] Emit Attributes

fud/fud/check.py
=> Outdated fud check link hotfix

.github/workflows/rust.yml, docs/frontends/ntt.md, docs/fud/index.md, frontends/ntt-pipeline/fud/ntt.py, frontends/ntt-pipeline/gen-ntt-pipeline.py, runt.toml, tests/frontend/ntt-pipeline/ntt-4-reduced-2.expect, tests/frontend/ntt-pipeline/ntt-4.expect
Defines an external fud stage for the NTT pipeline generator.
=> fud stage for NTT pipeline generator

src/backend/mlir.rs, tests/backend/mlir/with-guards.expect
=> [CIRCT] Change representation of guards.

src/backend/mlir.rs, tests/backend/mlir/attributes.expect, tests/backend/mlir/no-guards.expect, tests/backend/mlir/simple.expect, tests/backend/mlir/with-guards.expect
Blocked on https://github.com/llvm/circt/pull/1924.
=> [CIRCT] Add changes for symbolic instance names.

calyx/src/passes/reset_insertion.rs, examples/futil/dot-product.expect, examples/futil/multi-component.expect, examples/futil/pass-in-register.expect, examples/futil/simple.expect, examples/futil/vectorized-add.expect, tests/passes/regressions/group-multi-drive.expect
This would make things in #753 work so that's kinda cool.
=> [Passes] Reset all things.

calyx/src/ir/control.rs
We've generally avoided implementing this method up till now because it's not really a good idea to clone `Control` for most use cases. However, the inliner will need to use this method.
=> Define `Control::clone`

docs/fud/index.md, fud/fud/exec.py, fud/fud/main.py
=> [fud] Make `csv` its own flag and add documentation.

interp/src/interpreter/steppers/group_interpreter.rs, interp/src/structures/environment.rs
closes #792 
Note there is a discrepancy in the output which may or may not be a bug with something
=> [Interpreter] Patch sdiv mixup

interp/src/debugger/commands.rs
Small PR cleaning up the help message for CIDR and reorganizing how it is printed
=> [CIDR] Improve help message and change its organization

calyx/src/passes/resource_sharing.rs, tests/passes/resource-sharing/continuous-assign.expect, tests/passes/resource-sharing/continuous-assign.futil
=> Disallow sharing of cells used in continuous assignments

calyx/src/passes/papercut.rs
=> Remove papercut warning about continuously driven cells

benches/component-sharing.rs, benches/component-sharing/gemm2.futil, benches/component-sharing/gemm3.futil, benches/component-sharing/gemm4.futil, benches/component-sharing/gemm6.futil, benches/component-sharing/gemm8.futil
=> Fix benchmarks

docs/SUMMARY.md, docs/debug/cider.md, docs/debug/index.md
As discussed in #860, this PR adds some documentation for cider to the docs. This is non-exhaustive, but hopefully useful enough to get people who are curious started with the tool.
=> Add CIDR page to docs.

fud/fud/stages/__init__.py
Make the `convert_source_to` method available on the computation graph object. This is useful for stages with extra computation graphs where it is hard to specify the input should be a particular type.
=> `convert_source_to` method for `ComputationGraph`

calyx/src/analysis/dataflow_order.rs, calyx/src/analysis/graph.rs, calyx/src/errors.rs, calyx/src/ir/from_ast.rs, calyx/src/ir/mod.rs, calyx/src/ir/rewriter.rs, calyx/src/ir/structure.rs, calyx/src/passes/comb_prop.rs, calyx/src/passes/component_iniliner.rs, calyx/src/passes/hole_inliner.rs, calyx/src/passes/merge_assign.rs, calyx/src/passes/register_unsharing.rs, calyx/src/passes/remove_comb_groups.rs, calyx/src/passes/sharing_components.rs, calyx/src/passes/well_formed.rs, interp/src/structures/environment.rs, interp/tests/errors/multiple_drivers_comb.expect, interp/tests/errors/multiple_drivers_comb.futil, interp/tests/errors/multiple_drivers_reg.expect, interp/tests/errors/multiple_drivers_reg.futil, src/backend/verilog.rs, tests/errors/group-cont-assign-conflict.expect, tests/errors/group-cont-assign-conflict.futil, tests/errors/obvious-conflict.expect, tests/errors/obvious-conflict.futil
It is smart enough to detect conflicts between continuous assignments and group assignments.
=> `well-formed` can detect obvious conflicts

src/backend/verilog.rs, tests/backend/verilog/big-const.expect, tests/backend/verilog/big-const.futil
=> correctly emit large constants

Cargo.lock, Cargo.toml, calyx-py/calyx/py_ast.py, frontends/relay/relay_visitor.py, fud/fud/config.py, fud/fud/stages/interpreter.py, fud/fud/stages/relay.py, interp/Cargo.toml, interp/README.md, interp/src/debugger/cidr.rs, interp/src/debugger/context.rs, interp/src/debugger/mod.rs, interp/src/debugger/name_tree.rs, interp/src/debugger/source_location.rs, interp/src/errors.rs, interp/src/interpreter/component_interpreter.rs, interp/src/interpreter/control_interpreter.rs, interp/src/interpreter/group_interpreter.rs, interp/src/main.rs, interp/src/primitives/stateful.rs, interp/src/structures/environment.rs, interp/src/tests/primitives.rs
This adds the rudimentary source position tags, fixes a number of state machine bugs, also includes bounds checking warning per #900.
=> [Cider/Interpreter] Source position, misc bug fixing, bounds checking

frontends/relay/relay_visitor.py, interp/src/debugger/source/metadata.pest, interp/src/debugger/source/metadata_parser.rs
Works with newlines now as @sampsyo and I discussed in the prior PR #971
=> [Cider] Minor Tweaks to the Source pos parser

calyx/src/default_passes.rs, calyx/src/passes/mod.rs, calyx/src/passes/unroll_bound.rs, tests/passes/unroll-bound.expect, tests/passes/unroll-bound.futil
=> Pass to unroll `while` loops with `@bound`

.github/workflows/rust.yml, Cargo.lock, Cargo.toml, calyx/Cargo.toml, calyx/src/analysis/reaching_defns.rs, calyx/src/ir/context.rs, calyx/src/ir/guard.rs, calyx/src/ir/primitives.rs, calyx/src/ir/rewriter.rs, calyx/src/lib.rs, calyx/src/passes/minimize_regs.rs, calyx/src/passes/remove_comb_groups.rs, docs/SUMMARY.md, docs/compiler-as-library.md
Adds new [top-level documentation][source] for the source that shows how to use the `calyx` library to build new Calyx tools.
[source]: https://docs.calyxir.org/source/calyx/
=> update packages and docs

calyx/src/passes/well_formed.rs
=> Disallow multiple done conditions

calyx/src/default_passes.rs, docs/SUMMARY.md, docs/debug/debug.md, docs/debug/index.md
=> Update Debugging Advice

docs/lang/memories-by-reference.md
=> Information on new `ref` syntax for by-reference cells

calyx/src/passes/papercut.rs
=> Disable papercut check for done assignment when component has "nointerface" attribute

Cargo.lock
Just ran `cargo update` to get new shiny packages
=> update all packages

.github/workflows/rust.yml, calyx-py/calyx/py_ast.py, frontends/relay/relay_utils.py, frontends/relay/relay_visitor.py, runt.toml, tests/frontend/relay/batch_flatten-same-dimensions.expect, tests/frontend/relay/batch_flatten.expect, tests/frontend/relay/batch_matmul.expect, tests/frontend/relay/bias_add.expect, tests/frontend/relay/broadcast.expect, tests/frontend/relay/constant-multiply.expect, tests/frontend/relay/conv2d.expect, tests/frontend/relay/dense.expect, tests/frontend/relay/duplicate-relay-call.expect, tests/frontend/relay/max_pool2d.expect, tests/frontend/relay/negative.expect, tests/frontend/relay/relu.expect, tests/frontend/relay/reshape.expect, tests/frontend/relay/softmax.expect, tests/frontend/relay/sqrt.expect, tests/frontend/relay/tensor_add.expect
=> attempt to fix TVM github action

docs/lang/ref.md
I really like the new language reference introduced in #1066! I went through in detail and tried improving/expanding stuff along the way. Let me know if anything looks wrong!
=> [docs] Writing pass on the new language reference

calyx/src/analysis/live_range_analysis.rs, tests/passes/cell-share/while-no-share.expect, tests/passes/cell-share/while-no-share.futil, tests/passes/cell-share/while-write-guard.expect, tests/passes/cell-share/while-write-guard.futil
Also added a test case for this situation. Fixes #1135
=> Fixes LRA bug (#1135)

docs/frontends/tvm-relay.md
Added TVM documentation to help w/ error that I was encountering when trying to install.
=> added error message support for TVM docs

fud/fud/errors.py, fud/fud/registry.py
Distinguish between stage and state errors
=> Better fud error message

Cargo.lock, fud/fud/config.py, interp/Cargo.toml, interp/src/debugger/cidr.rs, interp/src/debugger/commands.rs, interp/src/debugger/io_utils.rs, interp/src/debugger/parser/command_parser.rs, interp/src/debugger/parser/commands.pest
This seems to have broken main. On running locally, the results for all interpreter integration tests just reports "null". @EclecticGriffin not sure what's wrong
=> Revert "[CIDR] Misc tweaks & help message changes (#1159)"

docs/frontends/tvm-relay.md, docs/tools/data-gen.md
=> Added data-gen documentation

fud/fud/stages/remote_context.py, fud/fud/stages/vivado/extract.py, fud/fud/stages/vivado/rpt.py, fud/fud/stages/vivado/stage.py
- Better error logging
- Robust data extraction
- Get worst slack information
=> Misc fixes for remote execution of vivado

calyx/src/passes/papercut.rs, examples/tutorial/language-tutorial-mem.futil, tests/errors/papercut/multi-done.expect, tests/errors/papercut/multi-done.futil, tests/errors/papercut/no-control-no-done.expect, tests/errors/papercut/no-control-no-done.futil, tests/passes/papercut-multi-done.expect, tests/passes/papercut-multi-done.futil
=> Fix Papercut For Multiple Go-Done Pairs

frontends/relay/dahlia_impl.py
Along with [this](https://github.com/cucapra/dahlia/pull/397) Dahlia PR, LeNet is correct now if we merge this PR. 
(Or at least as correct as it was with std_mem. There are still problems like #505, but overall the numbers are pretty close to when I run LeNet on TVM). 
Here's what was happening with LeNet: even though individually each operation (i.e., softmax, dense, max_pool2d, etc.) was being computed correctly (despite there being a flaw in the Calyx code), for some reason once I computed more than one operation in the same Calyx design it was giving me incorrect results-- in other words, the error in the Calyx code only started producing incorrect results once I was doing multiple operations together. So I think I may add a correctness test that does multiple operations on the same …
=> Fixes LeNet

frontends/relay/dahlia_impl.py, frontends/relay/image_processing.py, frontends/relay/onnx_to_calyx.py, frontends/relay/relay_utils.py, frontends/relay/relay_visitor.py, frontends/systolic-lang/gen-systolic.py, fud/fud/stages/verilator/json_to_dat.py, fud/fud/stages/verilator/numeric_types.py, fud/fud/stages/vivado/extract.py, fud/fud/stages/vivado/stage.py
Previously, getting an X-value was a hard error. This PR makes it a logging error and generates a final DAT file which might help point out where the error comes from.
=> Print out X-values in dat output

frontends/relay/dahlia_impl.py
Super small, not significant change that gets rid of error for AlexNet. 
Someday we may want to improve `reshape` to handle more cases, but this can work for now.
=> super small change

calyx/src/ir/attribute.rs, calyx/src/ir/from_ast.rs, calyx/src/ir/structure.rs, calyx/src/pass_manager.rs, calyx/src/passes/cell_share.rs, calyx/src/passes/group_to_seq.rs, calyx/src/passes/infer_static_timing.rs, calyx/src/passes/static_par_conv.rs, calyx/src/passes/synthesis_papercut.rs, interp/src/structures/state_views.rs, src/backend/mlir.rs, tests/passes/infer-static/comp-static.expect, tests/passes/infer-static/comp-static.futil
- Add timing specified timing information to latency_data
- Fix #1277
=> Correctly infer static timing for Calyx components

.vscode/launch.json, .vscode/settings.json, .vscode/tasks.json, calyx/src/utils/out_file.rs, src/backend/verilog.rs, tests/backend/verilog/big-const.expect, tests/backend/verilog/data-instance.expect, tests/backend/verilog/memory-with-external-attribute.expect
=> Generate program without buffering

calyx-py/calyx/builder.py, calyx-py/test/builder_example.py, frontends/ntt-pipeline/gen-ntt-pipeline.py
Plus some cleanup from @sampsyo's comments
=> Use builder in NTT 

calyx-py/calyx/builder.py, calyx-py/calyx/gen_exp.py, calyx-py/calyx/gen_ln.py, calyx-py/calyx/gen_msb.py, calyx-py/calyx/py_ast.py, calyx-py/test/example.py, calyx-py/test/if.py, calyx-py/test/invoke.py, frontends/mrxl/mrxl/gen_futil.py, frontends/ntt-pipeline/gen-ntt-pipeline.py, frontends/relay/relay_utils.py, frontends/relay/relay_visitor.py, frontends/systolic-lang/gen-systolic.py
Attempt 2 because rebasing the squashed commit didn't work
=> Turn `Stdlib` methods into static methods

frontends/relay/onnx_to_calyx.py, fud/fud/main.py, fud/fud/stages/verilator/__init__.py, fud/fud/stages/verilator/json_to_dat.py, fud/fud/stages/verilator/numeric_types.py, fud/fud/stages/verilator/stage.py
Data conversion states `mem-json` and `mem-dat` added to `fud` to enable quick performance testing of converting big files.
=> Explicit data conversion stages for `fud`

fud/fud/main.py
`fud` would previously automatically create fields in the configuration when `fud c <path> <val>` was provided and `<path>` didn't exist. This fails to catch problems where the path contains a typo. The user must explicitly pass the `--create` if they intended to create a new field.
=> fud: dont automatically create new fields in the config

fud/fud/errors.py, fud/fud/exec.py, fud/fud/stages/__init__.py, fud/fud/stages/dahlia.py, fud/fud/stages/futil.py, fud/fud/stages/verilator/stage.py, fud/icarus/icarus.py
=> Allow fud stages to specify known options

calyx/src/analysis/graph.rs, calyx/src/analysis/schedule_conflicts.rs, calyx/src/analysis/variable_detection.rs, calyx/src/default_passes.rs, calyx/src/ir/rewriter.rs, calyx/src/ir/structure.rs, calyx/src/passes/cell_share.rs, calyx/src/passes/component_iniliner.rs, calyx/src/passes/register_unsharing.rs
- Clean up some types
- log information in variablelike
- minor changes
- comm
=> Misc fixes

calyx/src/passes/top_down_compile_control.rs
Some minor code cleanup for TDCC
=> Cleanup tdcc code 

calyx/src/ir/traversal/mod.rs, calyx/src/ir/traversal/post_order.rs, calyx/src/ir/traversal/visitor.rs, calyx/src/passes/compile_ref.rs, calyx/src/passes/component_iniliner.rs, calyx/src/passes/infer_share.rs, calyx/src/passes/infer_static_timing.rs
Might overlap with what @anshumanmohan was planning to do
=> Enable pre-order traversal of components

calyx/src/analysis/live_range_analysis.rs, calyx/src/analysis/read_write_set.rs, calyx/src/ir/guard.rs, calyx/src/passes/group_to_seq.rs, tests/passes/cell-share/ignore_done.expect, tests/passes/cell-share/ignore_done.futil
Meant to address #1341. 
Something odd is happening in the testing though. For some reason, it's failing examples/sync/sync-if.futil. But when I try on my local, the test passes. Any ideas what could be going on? 
Edit: I realized that I had a mistake in my code. We want to be guaranteed that the `go` signal is written to in order to ignore the `done` signal. I didn't have that before (in other words, I had "maybe writes" when I should've had "must writes"). 
Weird though, because on my local I was still (I think) passing...
=> Improve lra

docs/fud/resource-estimation.md
=> Documentation for the resource estimation backend

docs/lang/ref.md, primitives/unsynthesizable.futil
As above. Maybe we should say more here, just not sure what! Please let me know if so!
=> Adding note about inlined primitives

fud/fud/check.py, fud/fud/config.py, fud/fud/main.py, fud/fud/registry.py, fud/fud/stages/__init__.py, fud/fud/stages/interpreter.py, fud/fud/stages/remote_context.py, fud/fud/stages/verilator/json_to_dat.py, fud/fud/stages/verilator/stage.py
- add externals to the default configuration
- warning instead of error
- fud check can take arguments representing stages to check
=> Fixes for Filament artifact

docs/fud/xilinx.md
As above! Let me know if I should change the wording!
=> Adding litmus test to Xilinx docs

.github/workflows/rust.yml
=> split out cocotb tests

calyx-py/calyx/builder.py, calyx-py/calyx/gen_exp.py, calyx-py/calyx/gen_ln.py
- per @sampsyo's comment, changed `sub_component` to `comp_instance`
- removed the set literal construction and replaced it with a `TypeError`
- additional docstrings and value checks
Closes #1517
=> [calyx-py] Minor bulider tweaks

Cargo.toml, interp/Cargo.toml
=> Add MSRV flags

.github/workflows/depot.yml, Dockerfile
A follow-up to #1538. Fingers continue to be crossed.
=> Fixes for the new Depot action

README.md
I was snooping and finally decided to implement a logo that can change the color of the text based on whether the browser is in dark mode.
=> Use magic logo for the readme

runt.toml
Configuring the expect directory as discussed! `runt -i 'mrxl correctness'` works as expected now!
=> Quick fix to add MrXL to CI

README.md
=> Proofreading: nit in README

docs/intro.md
=> Tutorial: update docker tag

CHANGELOG.md, calyx-frontend/src/workspace.rs
=> Make construct_with_all_deps public

calyx-frontend/src/common.rs
Fixes #1620! Seems pretty straightforward but let me know if there are any issues!
=> Derive `PartialEq` for `Width`

docs/debug/cider.md
I found broken links to fud and the interpreter. Easy fixes!
=> Docs: fix two links

CHANGELOG.md, calyx-frontend/src/common.rs, calyx-frontend/src/parser.rs, calyx-ir/src/builder.rs, calyx-ir/src/component.rs, calyx-ir/src/from_ast.rs, calyx-ir/src/printer.rs, calyx-ir/src/structure.rs, calyx-opt/src/analysis/dataflow_order.rs, calyx-opt/src/analysis/port_interface.rs, calyx-opt/src/passes/discover_external.rs, calyx-opt/src/passes/static_promotion.rs, src/backend/verilog.rs
=> Remove `PortDef::into`

src/backend/mlir.rs
Companion to https://github.com/llvm/circt/pull/5964
=> generate `calyx.undefined` for `undef` ops

src/cmdline.rs, src/driver.rs
=> add version information for the compiler

fud/fud/stages/xilinx/execution.py
This should probably fix #1724, superseding the `fix-pynq` branch (apparently @nathanielnrn and I stumbled on the same issue). We were setting the environment variables like `XCL_EMULATION_MODE=hw` in hardware-execution mode, where what we should be doing is not setting this at all in this mode.
To confirm that this works (and still works for emulation too), I produced two `xclbin`s from the same Calyx program: one for emulation (`lti.xclbin`) and one for real hardware (`lti.hw.xclbin`). Then I ran the two necessary fud commands to execute them:
```
$ fud exec -vv lti.hw.xclbin --from xclbin --to fpga -s fpga.data examples/tutorial/data.json -s xclbin.mode hw
$ fud exec -vv lti.xclbin --from xclbin --to fpga -s fpga.data examples/tutorial/data.json -s xclbin.mode hw_emu
```
Note the `-s …
=> [fud] Fix environment variables for real-FPGA runs

primitives/binary_operators.futil, primitives/binary_operators.sv
Add the sign extend primitive. Fixes #1009.
=> Add signext primitive

Dockerfile
We use runt `v0.4.0` for testing in Calyx
=> Use runt version 0.4.0

docs/contributors.md
Adding myself to the list of contributors after merging some PRs!!
=> Add Ayaka to list of contributors

calyx-opt/src/passes/cell_share.rs, calyx-opt/src/passes/static_promotion.rs, calyx-opt/src/traversal/construct.rs, tests/passes/cell-share/bounded.expect, tests/passes/cell-share/bounded.futil, tests/passes/cell-share/calyx_2020.expect, tests/passes/cell-share/calyx_2020.futil, tests/passes/cell-share/static-par.futil, tests/passes/par-timing-map/nested-par.expect, tests/passes/par-timing-map/nested-par.futil, tests/passes/par-timing-map/nested-while.expect, tests/passes/par-timing-map/nested-while.futil, tests/passes/par-timing-map/simple.expect, tests/passes/par-timing-map/simple.futil
Makes `cell-share` new the options API (#1814).
=> Register options for `cell-share`

calyx-py/calyx/py_ast.py, calyx-py/test/builder_example.expect, calyx-py/test/example.expect, tests/frontend/exp/degree-2-unsigned.expect, tests/frontend/exp/degree-4-signed.expect, tests/frontend/exp/degree-4-unsigned.expect, tests/frontend/ntt-pipeline/ntt-4-reduced-2.expect, tests/frontend/ntt-pipeline/ntt-4.expect, tests/frontend/relay/softmax.expect, tests/frontend/systolic/array-1.expect
=> Add parens around guard exprs

yxi/axi-calyx/axi-generator.py
Last PR of this kind for a while. This adds a generator for our hardcoded [`bresp` channel](https://github.com/calyxir/calyx/blob/main/yxi/axi-calyx/axi-combined-calyx.futil#L661-L701). As with #1855, #1856, #1861, tried to verify their similarity by inspection, but that is very error prone.
=> Add `calyx-py` AXI generator `bresp` channel

calyx-frontend/src/common.rs, calyx-ir/src/builder.rs, calyx-ir/src/from_ast.rs, tests/errors/insufficient-params.expect
=> Dont panic if insufficient parameters provided

Cargo.lock, Cargo.toml, fud2/fake/Cargo.toml, fud2/fake/src/cli.rs, fud2/fake/src/config.rs, fud2/src/main.rs
Logging to make it easier to see internals of `fud2`. Hopefully non-controversial enough that I can merge this without review!
=> Add logging to fud2

tools/firrtl/generate-firrtl-with-primitives.py, tools/firrtl/templates/std_const.fir, tools/firrtl/templates/std_lsh.fir, tools/firrtl/templates/std_reg.fir
I fixed some bugs in my initial FIRRTL implementations of Calyx primitives. I will make #1898 depend on this PR simply because I need to have both to test run my fud2 changes with the correct FIRRTL primitive implementations.
=> [Calyx-FIRRTL] Debugged FIRRTL implementations of primitives

docs/lang/attributes.md
Closes  #1429. 
Lmk if you think any more detail is needed on these.
=> Remove `@static` from docs

tools/firrtl/generate-firrtl-with-primitives.py, tools/firrtl/templates/std_ge.fir, tools/firrtl/templates/std_le.fir, tools/firrtl/templates/std_mult_pipe.fir
Another tiny PR! This one contains bug fixes for FIRRTL templates that I found while trying to run benchmarks. Also I wrote the template for `std_mult_pipe`.
=> [Calyx-FIRRTL] Primitive Template bug fixes and `std_mult_pipe` implementation

docs/lang/static.md
This PR adds a comment near the top of the [static keyword documentation](https://docs.calyxir.org/lang/static.html) to specify when it was introduced into the language.
=> Docs: version number and writing tweaks in page about `static`

fud2/fud-core/src/run.rs
This addresses a couple of requests from @EclecticGriffin! We now actually check the exit status of the `ninja` subcommand and handle errors. Concretely, this improves behavior in a few ways:
* better error messages when Ninja fails
* don't attempt to print stuff to stdout when Ninja fails
* clean up the `.fud2` temp directory even when Ninja fails
We discussed a bit on Slack whether the last one is actually desirable… there's a chance we might someday want a `keep_on_error` config option to return to the old behavior (i.e., `.fud2` is deleted by default but kept when Ninja fails). But let's wait for that to actually come up before implementing it…
=> [fud2] Check Ninja exit status and report errors

calyx-ir/src/utils.rs, yxi/tests/backend/dyn-mem-d4-add.expect, yxi/tests/backend/dyn-mem-d4-add.futil
Refactors a bit of code as well as adding a runt test for `dyn_mem`s in the `yxi` tests.
=> Update `yxi` to support `dyn_mem`s

calyx-opt/src/passes/top_down_compile_control.rs, runt.toml, tests/passes/tdcc-ohe/par.expect, tests/passes/tdcc-ohe/par.futil
Implements changes suggested in Tdcc ohe (PR #2087). Refactors `realize_schedule` and integrates with new changes to main. Adds correctness and snapshot tests.
=> new dynamic ohe branch due to weird git stuff

interp/src/flatten/primitives/builder.rs, interp/src/flatten/structures/environment/env.rs
Part of #1913.
Closes #2159.
May need to tweak the logging in the future.
=> [Cider 2] Add warning for unused initialization

data-conversion/src/main.rs
Quoting @Angelica-Schell:
> This pull request includes fixed to binary and binary to fixed conversion using multiplication and getting the exponent from the command line.
This is a successor to #2100, #2089, and #2090.
=> Data conversion: float/fixed conversion using FP multiplication

cider-dap/calyxDebug/built/extension.js, cider-dap/calyxDebug/extension.ts
Fixed issue mentioned in #2091 where debugging in multi session would crash. Also did some general code cleanup + refactoring and added a bit of documentation.
=> Cider-dap launch issues fix

.hooks/pre-commit, docs/intro.md, setup_hooks.sh
Automatically `cargo clippy` before you commit
=> Add git hooks and setup

docs/debug/cider.md
Update the docs page for Cider itself that I missed earlier
=> [Cider2] update the documentation page

fud2/scripts/cider.rhai, fud2/tests/snapshots/tests__test@calyx_cider-debug.snap, fud2/tests/snapshots/tests__test@calyx_cider_dat.snap, fud2/tests/snapshots/tests__test@plan_calyx-to-cider.snap, fud2/tests/snapshots/tests__test@plan_cider.snap
Small patch for an issue with the debugger path
=> [Cider 2] Fix a bug in the fud2 path

fud2/fud-core/src/run.rs
The error message has been changed from
```
No such file or directory (os error 2)
```
to
```
Error: Unable to run ninja "No such file or directory (os error 2)"
Hint: Is ninja installed correctly?
```
This is intended to close #2254
=> [fud2] Improve Error Message When Ninja Is Not Installed

interp/src/configuration.rs, interp/src/debugger/commands/command_parser.rs, interp/src/debugger/commands/commands.pest, interp/src/debugger/commands/core.rs, interp/src/debugger/commands/mod.rs, interp/src/debugger/debugger_core.rs, interp/src/debugger/debugging_context/context.rs, interp/src/debugger/source/mod.rs, interp/src/debugger/source/structures.rs, interp/src/errors.rs, interp/src/flatten/flat_ir/attributes.rs, interp/src/flatten/flat_ir/base.rs, interp/src/flatten/flat_ir/cell_prototype.rs, interp/src/flatten/flat_ir/control/structures.rs, interp/src/flatten/flat_ir/control/translator.rs, interp/src/flatten/flat_ir/identifier.rs, interp/src/flatten/flat_ir/mod.rs, interp/src/flatten/flat_ir/wires/core.rs, interp/src/flatten/flat_ir/wires/guards.rs, interp/src/flatten/flat_ir/wires/mod.rs, interp/src/flatten/mod.rs, interp/src/flatten/primitives/builder.rs, interp/src/flatten/primitives/prim_trait.rs, interp/src/flatten/structures/context.rs, interp/src/flatten/structures/environment/env.rs, interp/src/flatten/structures/printer.rs, interp/src/main.rs
Minor refactoring a documentation pass
=> [Cider] Documentation pass

fud2/Cargo.toml, fud2/fud-core/Cargo.toml
Adds a minimum rust version to `fud2` and `fud-core`.
=> Add fud2 minimum rust version.

interp/src/flatten/structures/environment/traverser.rs
Small fix for name traversal resolution
=> [Cider] Fix traversal bug

docs/tutorial/frontend-tut.md
861a42798461e8bc7ccbd41ce9b603171824eecc moved the location of `ast.py`. This PR adjusts sources to changes.
=> Update MrXL AST reference

calyx-opt/src/passes/cell_share.rs, calyx-opt/src/passes/infer_share.rs, calyx-opt/src/passes/top_down_compile_control.rs, calyx-utils/src/out_file.rs, src/cmdline.rs, tools/component_cells/src/main.rs
=> OutputFile calls create just once per run

calyx-frontend/src/parser.rs, calyx-frontend/src/syntax.pest, calyx-ir/src/printer.rs, calyx-utils/src/float.rs, calyx-utils/src/lib.rs, docs/libraries/core.md, primitives/float.futil, runt.toml, tests/errors/float/invalid-rep.expect, tests/errors/float/invalid-rep.futil, tests/errors/float/invalid-width.expect, tests/errors/float/invalid-width.futil, tests/parsing/float.expect
=> Floating-point Constants

calyx-ir/src/reserved_names.rs
=> Add `wait` and `break` to reserved names

fud2/fud-core/src/script/plugin.rs, fud2/scripts/calyx.rhai, fud2/tests/snapshots/tests__test@calyx_through_cider_to_dat.snap, fud2/tests/snapshots/tests__test@calyx_through_firrtl_to_verilog-refmem.snap, fud2/tests/snapshots/tests__test@calyx_through_icarus_to_dat.snap, fud2/tests/snapshots/tests__test@calyx_through_icarus_to_vcd.snap, fud2/tests/snapshots/tests__test@calyx_through_verilator_to_dat.snap, fud2/tests/snapshots/tests__test@calyx_through_verilator_to_vcd.snap, fud2/tests/snapshots/tests__test@calyx_through_xrt-trace_to_vcd.snap, fud2/tests/snapshots/tests__test@calyx_through_xrt_to_dat.snap, fud2/tests/snapshots/tests__test@calyx_to_cider-debug.snap, fud2/tests/snapshots/tests__test@calyx_to_verilog.snap, fud2/tests/snapshots/tests__test@plan_axi-wrapped.snap, fud2/tests/snapshots/tests__test@plan_calyx-noverify.snap, fud2/tests/snapshots/tests__test@plan_calyx-to-cider.snap, fud2/tests/snapshots/tests__test@plan_calyx-to-cocotb-axi.snap, fud2/tests/snapshots/tests__test@plan_calyx-to-firrtl.snap, fud2/tests/snapshots/tests__test@plan_calyx-to-verilog.snap, fud2/tests/snapshots/tests__test@plan_calyx-to-yxi.snap, fud2/tests/snapshots/tests__test@plan_cider.snap, fud2/tests/snapshots/tests__test@plan_debug.snap, fud2/tests/snapshots/tests__test@plan_firrtl-with-primitives.snap, fud2/tests/snapshots/tests__test@plan_primitive-uses.snap, fud2/tests/snapshots/tests__test@plan_profiler.snap, fud2/tests/snapshots/tests__test@plan_xo.snap
Add a `calyx.lib_path` argument for the `fud2` stage.
=> Separate flag for specifying lib path in `fud2`

docs/running-calyx/profiler.md, tools/profiler/profiler-process.py
This PR contains some improvements and fixes to the timeline view:
- Group names are no longer fully qualified
- FSM values were not being read correctly after #2430, but this is now fixed
I also updated the docs to list Graphviz as a dependency. Thanks @pedropontesgarcia for pointing this out!
=> [Profiler] Timeline view small fixes + dependency documentation

Cargo.lock, cider/Cargo.toml, cider/idx/src/index_trait.rs, cider/idx/src/indexed_map.rs, cider/idx/src/sparse_map.rs, cider/src/debugger/debugger_core.rs, cider/src/debugger/debugging_context/context.rs, cider/src/flatten/flat_ir/base.rs, cider/src/flatten/flat_ir/component.rs, cider/src/flatten/flat_ir/control/structures.rs, cider/src/flatten/structures/environment/assignments.rs, cider/src/flatten/structures/environment/env.rs, cider/src/flatten/structures/environment/maps.rs, cider/src/flatten/structures/environment/mod.rs, cider/src/flatten/structures/environment/program_counter.rs
Just some light refactoring of the `env` file and associated rearranging. Nothing too exciting. Biggest change is use of `delegate!` macro to simplify the many method delegations
=> [Cider] Misc refactoring

fud2/scripts/relay.rhai, fud2/tests/snapshots/tests__list_ops.snap, fud2/tests/snapshots/tests__list_states.snap, fud2/tests/snapshots/tests__test@plan_relay.snap, runt.toml
An attempt at adding `relay` which I'm not certain works. CI will hopefully tell me if there are problems
=> [Fud2] Attempt at adding `relay` op

docs/contributors.md
Old website's domain got bought by a spam company. Probably a good idea to remove.
=> Update Jan-Paul's website

docs/running-calyx/profiler.md
Recommending to use `--through profiler` now that we have multiple ops that go to the `flamegraph` state thanks to @pedropontesgarcia 's work!!
=> Update profiler documentation

tools/profiler/profiler/visuals/utilization_plots.py
2 character fix of a tiny bug.
=> [Profiler] Quick fix for ratio calculation

docs/running-calyx/fud2/index.md, fud2/fud-core/src/log_parser.rs
=> CSV fixes and some light documentation

fud2/fud-core/src/cli_ext.rs, fud2/fud-core/src/uninterrupt.rs
Does what it says on the tin. Some of the doc tests fail and now they don't.
=> [fud2] Fix failing doc tests in fud-core
