calyxir/calyx

src/ast.rkt, src/component.rkt, src/constraint.rkt, src/futil-prims.rkt, src/futil-syntax.rkt, src/futil.rkt, src/port.rkt, src/vizualizer.rkt
Some quick refactoring using magic racket stuff. Notes
- `match-define` (and other functions in `racket/match`) are super useful for destructuring any (and I do mean any) kind of data. Worth reading up on.
- `begin` is inconsistently used by Racket. Always worth checking if you actually need to use it (for example match branches don't!)
- `racket/base` loads faster than racket. However, macro heavy files are annoying to switch to `racket/base`.
=> Refactorings

src/backend/verilog/gen.rs, src/lang/ast.rs, src/lang/component.rs, src/lang/context.rs, src/lang/library/ast.rs, src/lang/pretty_print.rs, src/lang/structure.rs, src/passes/redundant_par.rs, src/passes/remove_if.rs
This PR makes `ast::Id` a structure rather than a type alias. This
means that it will be easier in the future to add fields to identifiers (such as src locations).
I've provided several trait implementations for `ast::Id`s to make them behave
more like strings and thus lighter weight to use.
- remove doc comments
- make id a new type rather than a type alias
=> Use newtype for ast::Id

.github/workflows/rust.yml, .gitignore, Cargo.toml, src/backend/traits.rs, src/backend/verilog/gen.rs, src/cmdline.rs, src/lang/ast.rs, src/lang/component.rs, src/lang/context.rs, src/lang/library/ast.rs, src/lang/pretty_print.rs, src/lang/structure.rs, src/main.rs, src/passes/redundant_par.rs, src/passes/remove_if.rs
Addresses issue #68 by adding a cmdline option to select which backend to use. 
The available backends are specified by `cmdline::BackendOpt` and the corresponding
`FromStr` and `ToString` trait implementations for it. For now, the backend names
are specified in `cmdline.rs` rather than in the backends directly.
=> Backend CLI

calyx/src/passes/collapse_seq.rs, calyx/src/passes/redundant_par.rs, calyx/src/passes/remove_if.rs, calyx/src/passes/visitor.rs
Changes all the visitor functions to take immutable references
to their control nodes. This forces using the `Action::Change` pattern
to update nodes which allows the visitor framework to define what happens
when part of the AST changes during traversal.
=> Remove visitor control mutability

calyx/src/passes/collapse_seq.rs, calyx/src/passes/lat_insensitive.rs, calyx/src/passes/redundant_par.rs, calyx/src/passes/remove_if.rs, calyx/src/passes/visitor.rs
This pass moves pass naming into a separate trait called `Named`.
This allows the naming functions to have type `fn() -> &'static str` instead
of `fn(&self) -> String`. This allows access to the name and description of a
pass without first instantiating the associated pass struct.
=> Static pass naming

runt.toml
- Runt configuration tracks version of tool being used using `ver`. 
- Uses `expect_dir` to change the location of `.expect` files. This will allow us to use the same input files for multiple test suites.
=> upgrade runt configuration

Makefile, bin/gen-vcd
Move the longer bash sequences into a script so that we can check them
with `shellcheck`, emit good error messages, and avoid the various weird
behavior make has.
=> Scriptify longer bash command in Makefile.

relay-futil/README.md, relay-futil/example.py
This just steals the [MLP DNN](https://github.com/apache/incubator-tvm/blob/master/python/tvm/relay/testing/mlp.py) directly out of the [Relay tests](https://github.com/apache/incubator-tvm/tree/master/python/tvm/relay/testing). It results in pretty straightforward high-level IR:
```
fn (%data: Tensor[(1, 1, 28, 28), float32], %fc1_weight, %fc1_bias, %fc2_weight, %fc2_bias, %fc3_weight, %fc3_bias) {
%0 = nn.batch_flatten(%data);
%1 = nn.dense(%0, %fc1_weight, units=128);
%2 = nn.bias_add(%1, %fc1_bias, axis=-1);
%3 = nn.relu(%2);
%4 = nn.dense(%3, %fc2_weight, units=64);
%5 = nn.bias_add(%4, %fc2_bias, axis=-1);
%6 = nn.relu(%5);
%7 = nn.dense(%6, %fc3_weight, units=10);
%8 = nn.bias_add(%7, %fc3_bias, axis=-1);
nn.softmax(%8)
}
```
I also added an `-o` flag to the example script that …
=> Add a real DNN to the Relay examples

README.md
Let me know if you think this is unhelpful or too verbose. Also, maybe it would be helpful to actually have an ```examples/simple.futil```? Or, is there already one and I'm just not finding it?
Closes #209
=> [README] Fix -l command to avoid double path.

README.md, examples/simple.futil
This adds an example to the main FuTIL repository, a part of #215 .
This code is a quick snapshot of FuTIL components, and is used mostly so that the code in the README at https://github.com/cucapra/futil#compiler-development works.
=> Add simple example that falls in line with README

benchmarks/print_headers/printer.cpp
Since values are not being modified, this should use constant references of the vectors. Similarly, we can use a ranged for loop to avoid index out-of-bounds errors.
I'm not quite sure of its use case here, but it would be more efficient to use a single std::vector as well, and use row-major ordering. Though, if this isn't a bottleneck of any sorts, then no need to change.
=> [benchmarks] Use constant reference for vectors.

frontends/relay-futil/README.md
Prefer `&&` over `;` so that it ends upon failure.
Eventually, once I'm more familiar, I'll look into moving this to the Rust docs.
=> [wip] Small nit changes in Relay README

calyx/src/backend/verilog.rs, fud/sim/testbench.cpp
Fixes #284.
Lack of initial inputs causes a zero-time reset bug in simulation. See verilator/verilator#2661.
=> Fixes to avoid zero-time reset bug in simulation

calyx/src/errors.rs, calyx/src/frontend/ast.rs, calyx/src/frontend/futil_syntax.pest, calyx/src/frontend/parser.rs, calyx/src/ir/from_ast.rs, calyx/src/passes/well_formed.rs, tests/errors/duplicate-cells.expect, tests/errors/duplicate-cells.futil, tests/errors/papercut-cell-and-group-conflict.expect, tests/errors/papercut-cell-and-group-conflict.futil, tests/errors/papercut-cell-as-group.expect, tests/passes/go-insertion.futil, tests/passes/minimize-regs/thread-local.futil
Breaking change: Require components to have signature.
For example, these are now invalid:
```
component main { ... }
component main() { ... }
```
The only allowed form is:
```
component main() -> () { ... }
```
Relentlessly pursue consistency.
=> Cull Frontend AST

primitives/std.lib
This was missing from a previous CL I believe, since `fixed_p_std_gt` is supported.
=> Add fixed_p_std_sgt.

calyx/src/frontend/ast.rs, calyx/src/frontend/futil_syntax.pest, calyx/src/frontend/parser.rs, calyx/src/ir/attribute.rs, calyx/src/ir/builder.rs, calyx/src/ir/component.rs, calyx/src/ir/control.rs, calyx/src/ir/from_ast.rs, calyx/src/ir/mod.rs, calyx/src/ir/primitives.rs, calyx/src/ir/printer.rs, calyx/src/ir/structure.rs, calyx/src/ir/traversal/visitor.rs, calyx/src/passes/compile_control.rs, calyx/src/passes/compile_empty.rs, calyx/src/passes/compile_invoke.rs, calyx/src/passes/infer_static_timing.rs, calyx/src/passes/resource_sharing.rs, calyx/src/passes/static_timing.rs, calyx/src/passes/top_down_compile_control.rs, tests/errors/mismatch-widths.expect, tests/errors/parser/cell-missing-semi.expect, tests/errors/parser/cell-missing-semi.futil, tests/parsing/attributes.futil
Add attribute points for components, cell declarations, and port definitions:
```
import "primitives/core.futil";
component main<"static"=1>(@stable(1) @go_port(1) in: 32) -> (@stable(0) out: 32) {
cells {
@precious(1) out = prim std_reg(32);
le = prim std_le(32);
}
wires {
group cond<"stable"=1> {
cond[done] = 1'd1;
}
}
control {
}
}
```
Fixes #311.
=> Add attribute points

calyx/src/ir/attribute.rs, calyx/src/ir/context.rs, calyx/src/passes/infer_static_timing.rs
Makes `infer-static-timing` use port attributes to figure out which ports
primitives correspond to the `go`/`done` interface.
The benefit of doing this is that adding a new primitive to `infer-static-timing`
only requires us to add attributes.
The pass definition does not have to change.
Fixes #341.
=> make infer-static-timing use port attributes to get go/done ports

calyx/src/ir/traversal/mod.rs, calyx/src/ir/traversal/post_order.rs, calyx/src/ir/traversal/visitor.rs, calyx/src/passes/compile_invoke.rs, calyx/src/passes/infer_static_timing.rs, src/main.rs, tests/passes/compile-invoke.expect, tests/passes/compile-invoke.futil, tests/passes/infer-static/invoke.expect, tests/passes/infer-static/invoke.futil
Changes `infer-static-timing` to use `require_postorder` and uses `"static"` annotations calculated on components to add static timing information on `invoke` statements.
`compile-invoke` is changed to copy the `static` attribute on the control node to the generated group.
=> Infer static timing adds annotations to invoke

primitives/bitnum/unsigned.sv
Changes to make `std_sqrt` instances `invoke`-able.
- Change primitive to latch `out`
=> Invoke sqrt

calyx/src/analysis/graph.rs, calyx/src/passes/mod.rs, calyx/src/passes/synthesis_papercut.rs, runt.toml, src/main.rs, tests/errors/mem-only-reads.expect, tests/errors/mem-only-reads.futil
New pass that generates and error when a memory is only used for reads or writes without @external(1). This pass should be enabled for the default synthesis alias.
Fixes #384.
=> Synthesis Papercut: Error read-only and write-only memories

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, .gitignore, .vscode/launch.json, .vscode/settings.json, .vscode/tasks.json
I've added support for Visual Studio Code and it's Remote-Containers extension, to make development setup a bit easier, for example:
https://dev.to/ctison/vscode-remote-containers-5740
The PR is based off of Microsoft's own container for Rust development, which uses a Debian container underneath: 
https://github.com/microsoft/vscode-remote-try-rust
=> Support for Visual Studio Code & the Remote-Containers Extension

docs/lang/attributes.md, docs/tutorial/frontend-tut.md, docs/tutorial/language-tut.md
This PR attempts to make minor adjustments to parts of the tutorial documentation with `prim` prefix still being used.
=> [Docs] Tutorial hotfix

calyx/src/frontend/parser.rs, tests/errors/parser/invalid-width.expect, tests/errors/parser/invalid-width.futil, tests/errors/parser/invalid-width2.expect, tests/errors/parser/invalid-width2.futil, tests/errors/parser/invalid-width3.expect, tests/errors/parser/invalid-width3.futil, tests/errors/parser/invalid-width4.expect, tests/errors/parser/invalid-width4.futil
Adds parser error messages for literals that cannot be represented in the given bitwidth. Closes #438.
Will need to be adjusted later to support zero width literals like `0'null`
=> Parser tweaks

docs/contributors.md, docs/tutorial/language-tut.md
Old docs referred to cells in the part of the tutorial that referred control.
=> Fix tutorial docs + add to contributors

calyx/src/analysis/graph_coloring.rs, calyx/src/passes/sharing_components.rs, calyx/src/utils/measure_time.rs, calyx/src/utils/mod.rs, calyx/src/utils/weight_graph.rs, tools/emacs/futil-mode/futil-mode.el
Fixes resource sharing performance regression (#459) by:
1) not adding conflict edges between cells of different types
2) updating graph coloring algorithm to take account of node types when assigning colors to nodes.
=> Sharing component perf fix

calyx/src/ir/id.rs, interp/src/environment.rs, interp/src/interpret_component.rs, interp/src/interpret_control.rs, interp/src/interpret_group.rs, interp/src/interpreter.rs, interp/src/primitives.rs, interp/src/update.rs
Just a series of small changes to clean up various pieces of the existing interpreter code. Replacing the custom printing structure with a direct implementation of serde serialize. Adding `todo!()` in a few places. Replacing use of `String` w/ `ir::Id` where appropriate and removing some code made obsolete by this change.
=> Interpreter cleaning

calyx/src/ir/traversal/visitor.rs, calyx/src/passes/inliner.rs, calyx/src/passes/papercut.rs, calyx/src/passes/top_down_compile_control.rs, tests/backend/verilog/memory-with-external-attribute.expect, tests/backend/verilog/memory-with-external-attribute.futil, tests/errors/papercut-no-control-no-done.expect, tests/errors/papercut-no-control-no-done.futil, tests/passes/compile-empty.expect, tests/passes/compile-empty.futil
Fix behavior of compile-empty and other passes when the input program truly has an empty control block.
=> Dont insert empty group when control is completely empty

calyx/src/analysis/reaching_defns.rs, tests/passes/unsharing/while.expect
Tiny patch for #526. The issue was the analysis not being appropriately conservative with respect to the while loop and allowing the while loop to kill definitions that should not be killed due to being re-introduced through the cond (i.e. not assuming that the while always runs).
This wasn't noticed previously because the test happened to still be correct with this non-conservative assumption. 
@rachitnigam if you could re-run your benchmark tests or point me in the right direction, I would be very grateful.
=> Unsharing bug

calyx/src/frontend/futil_syntax.pest, calyx/src/frontend/parser.rs, calyx/src/ir/printer.rs, examples/futil/dot-product.expect, examples/futil/vectorized-add.expect, tests/parsing/attributes.expect, tests/passes/guard-canonicalize.expect, tests/passes/infer-static/bounded-loop.expect, tests/passes/infer-static/component.expect, tests/passes/infer-static/groups.expect, tests/passes/infer-static/invoke.expect, tests/passes/minimize-regs/live-register-analysis.expect, tests/passes/minimize-regs/par-while-liveness.expect
Parser now supports `@external` syntax for attributes and defaults the value to one.
This means `@external` is the same as `@external(1)`.
=> Support bare @ attribute syntax

calyx/src/ir/id.rs, fud/fud/config.py, fud/fud/main.py, fud/fud/stages/interpreter.py, interp/src/environment.rs, interp/src/lib.rs, interp/src/main.rs, interp/src/primitives.rs, interp/src/utils.rs, interp/src/values.rs, interp/tests/while.futil.data
An attempt to close #560.
Major changes include:
***fud support for invoking the interpreter***
try `fud e --to interpreter-out ...`
***fud support for passing data files to the interpreter***
try `fud exec --to interpreter-out tests/while.futil -s interpreter.data tests/while.futil.data `
***Interpreter can now take and initialize memories based on the data marshaled from fud***
***memories are now a flat vec with row-major ordering indexing***
***NEW SERIALIZATION CRIMES***
Anyway, this still needs a bit of work, mainly in the writing tests department. But also someone please check my work wrt the row-major ordering calculations because I don't know that I did them correctly.
Also there's a bug in `tests/while.futil` for the interpreter since the addr0 of the memory is never set and the …
=> Fud interpreter integration

fud/fud/stages/interpreter.py, fud/fud/stages/verilator/json_to_dat.py
At some point, fud started using a float-to-fixed conversion utility from the calyx-py library. I think this was a mistake because calyx-py is really just for Calyx code generators (frontends); it's not, like, a general-purpose library for all things Calyx. And because this dependency was undeclared, it meant that someone following our setup instructions would end up with a "broken" fud and would need to go back and install calyx-py as well.
This duplicates that utility function, which removes the accidental dependency. I think it's not too much of a sin to copy & paste the code because it's so little code. I also thought the original docstring was somewhat inaccurate, so I tried a slightly better one.
=> Remove an accidental dependency for fud

docs/fud/examples.md, docs/interpreter.md
This just expands the docs a little to show how to use the interpreter via fud. The examples are based on @EclecticGriffin's commands from #583. (Basically, I just tried all this out myself and recorded how I figured out how to do it.)
=> Expand interpreter docs

docs/lang/attributes.md
This adds a few things:
* Use the shorthand `@attr` syntax introduced in #566, where appropriate.
* Document the `@reset` attribute added in #579. Also, slightly expand the discussion of the role of it, `@go`, and `@done`, although this topic probably needs a deep discussion of its own someday.
* Document the `@clk` attribute (tersely).
=> Update attribute documentation

interp/runt.toml, runt.toml
New version of runt (0.3.1) is out! You'll have to run `cargo install runt`
to get the latest version.
Please report any problems to: https://github.com/rachitnigam/runt/issues/new
=> upgrade runt version

Cargo.toml, interp/Cargo.toml, interp/src/main.rs, src/cmdline.rs, src/main.rs
This removes 18 dependencies from the build of the compiler.
=> Use `argh` instead of `structopt` for parsing

calyx/src/analysis/graph.rs, calyx/src/analysis/live_range_analysis.rs, calyx/src/analysis/reaching_defns.rs, calyx/src/analysis/read_write_set.rs, calyx/src/analysis/variable_detection.rs, calyx/src/ir/mod.rs, calyx/src/ir/primitives.rs, calyx/src/ir/structure.rs, calyx/src/ir/traversal/visitor.rs, calyx/src/passes/dead_cell_removal.rs, calyx/src/passes/infer_static_timing.rs, calyx/src/passes/papercut.rs, calyx/src/passes/resource_sharing.rs, calyx/src/passes/well_formed.rs, docs/lang/attributes.md, interp/tests/control/iteration/while.futil, primitives/binary_operators.futil, primitives/core.futil, primitives/math.futil, tests/correctness/while.futil, tests/errors/no-drive.expect, tests/errors/papercut-no-done.expect, tests/errors/papercut-no-done.futil, tests/errors/papercut-read-missing-write.expect, tests/errors/papercut-read-missing-write.futil, tools/vim/futil/syntax/futil.vim
Adds two new annotations:
- `@write_together(n)`: All signals in group `n` must be written to when any
signal in group `n` is written to.
- `@read_together(n)`: When the *only* output signal associated with group `n` is read,
input signals in group `n` must be written to.
Examples:
1. For `std_reg`, `.in` and `.write_en` are in the same `@write_together` group.
2. For `std_mem_d1`, `.read_data` and `.addr0` are in the same `@read_together` group.
Note that `@write_together` annotation creates a set so we can't specify something like
"when `.in` is used in `std_mem_d1` then `.addr0` should also be driven".
This is because it is not the case that `.in` should be driven when `.addr0` is driven.
=> Annotations for specifying that signals should be used together

interp/src/primitives/stateful.rs
A simple patch which makes memories return zero when given an invalid index and raise an error if the clock ticks with an invalid index. This means that transient index changes during convergence won't cause spurious errors, but that lasting incorrect indices will appropriately raise an error.
I don't believe there was an issue open for the error, but please correct me if I'm wrong
=> Patch out-of-bounds memory on durbin

fud/fud/config.py, fud/fud/exec.py, fud/fud/main.py, fud/fud/stages/__init__.py, fud/fud/stages/interpreter.py, fud/fud/utils.py
A small hack to enable `fud` to work with the interactive debugger. This was complicated slightly by the need to use standard input & output directly which is a bit different from fud's normal behavior.
The end result is that now you can use `--to debugger` to get the interactive debugger and use `-s interpreter.debugger.flags` to pass flags directly to the debugger. It is an alternate stage of the interpreter and so plugs into the same places that the interpreter does.
Given that this is more than a bit hacky, I'd appreciate some eyes on it.
=> Fud support for the interactive debugger

calyx/src/backend/verilog.rs, runt.toml, tests/backend/verilog/memory-with-external-attribute.expect, tests/errors/runtime/multiple-drivers.expect, tests/errors/runtime/multiple-drivers.futil
#614 remains blocked on https://github.com/verilator/verilator/issues/3088 and I don't want to try to fix the bug in the Verilator source code.
This PR uses the transformation Verilator performs to add a dynamic check that ensure that each port has a unique driver. The generated code looks something like this:
```
always_comb begin
if(~$onehot0({fsm_out != 1'd1 & go, fsm_out == 1'd1})) begin
$error("Multiple assignment to port fsm.in");
end
end
```
Closes #614.
=> Dyanmically check for unique drivers

benches/component-sharing.rs, calyx/src/ir/context.rs, calyx/src/ir/from_ast.rs, interp/src/main.rs, src/backend/verilog.rs, src/cmdline.rs, src/main.rs
This is stopgap measure to get master to be green again for now. A long-term solution would require fixing the Dahlia frontend to generate code that doesn't fail the asserts in the generated Verilog.
=> Add CLI flag to disable asserts in verilog backend

src/backend/circt.rs
Closes #644.
Side note: It would be nice to have the number of dimensions as a parameter as well, e.g. `std_mem(/*numDims=*/1, 32, 1, 1);` I think we talked about this before, using row major ordering.
=> [CIRCT] Fix MemoryOp representation, Add 3/4D memory.

.github/workflows/integration.yml, interp/src/interpreter/interpret_component.rs, interp/src/interpreter/interpret_control.rs
Closes #649.
Fixes a silly bug causing incorrect behavior on empty groups when running through the normal interpreter pass.
The unrolled ones now crash due to multiple-par writes, as anticipated.
~Note: may wish to use the `control_is_empty` function from the stepper utils rather than only matching a top level empty.~ done
=> Patch inifinite unroll bug

calyx/src/passes/top_down_compile_control.rs
Some reorganization I ended up doing while trying to fix #662.
Instead of having both `calculate_states_recur` and `control_exits` compute
`cur_state`, `tdcc` will just add the `@NODE_ID` to enable and par blocks.
The exact schema for these NODE_IDs is defined by `compute_unique_ids`.
The method for computing these IDs is almost identical to #653 but is not
exposed to the rest of the compiler.
A different PR can perform the refactoring needed to expose this to rest of
the compiler.
NFC: No functional change
=> [NFC] `tdcc`: Generate unique-ids for control nodes during compilation

interp/src/environment.rs, interp/src/errors.rs, interp/src/primitives/stateful.rs
A small patch which closes #675.
Currently just unwraps the error so it will still cause a panic, but the message should be more useful going forward.
=> Make the error message for incorrect memory initialization more useful

fud/fud/exec.py, fud/fud/main.py, fud/fud/stages/__init__.py, fud/fud/stages/verilator/stage.py, fud/fud/utils.py
Some examples:
```bash
stage                           elapsed time (s)
futil                           0.067
icarus-verilog                  0.24
```
```bash
icarus-verilog                  elapsed time (s)
mktmp                           0.0
json_to_dat                     0.002
compile_with_iverilog           0.025
simulate                        0.127
output_json                     0.003
cleanup                         0.001
futil                           elapsed time (s)
run_futil                       0.028
```
```bash
futil,run_futil,0.029
icarus-verilog,mktmp,0.0
icarus-verilog,json_to_dat,0.002
icarus-verilog,compile_with_iverilog,0.024
icarus-verilog,simulate,0.128
icarus-verilog,output_json,0.003
icarus-verilog,cleanup,0.001
```
Allows file writes as well using the `-o` flag. …
=> [fud] Add CSV and normal profiling flags.

fud/fud/exec.py, fud/fud/stages/__init__.py, fud/fud/utils.py
Remove `args` from run(), since it is no longer used, and a few other small changes. Semantics remain the same.
=> [NFC] Cleanup profiling.

docs/fud/index.md, fud/fud/errors.py, fud/fud/exec.py, fud/fud/stages/__init__.py, fud/fud/utils.py
Adds step-based profiling, e.g.
```bash
fud e examples/futil/memory-by-reference/memory-by-reference.futil --to dat \
-s verilog.data examples/futil/memory-by-reference/memory-by-reference.futil.data \
--through icarus-verilog \
-pr icarus-verilog.cleanup icarus-verilog.output_json -csv
```
will output:
```python
icarus-verilog,output_json,0.001
icarus-verilog,cleanup,0.002
```
All other profiling behavior remains the same, i.e. if you provide no steps, then all steps will be printed.
=> [fud] Add step-based profiling.

fud/fud/exec.py, fud/fud/stages/interpreter.py
After execution, Fud is looking for a SourceType.String, not SourceType.Stream.
=> [fud] Fix return type of `interpret` stage.

docs/interpreter.md
Squashes the example in the interpreter documentation.
=> [docs] Use verilog.data instead of interpreter.data

calyx/src/ir/component.rs, calyx/src/ir/from_ast.rs, calyx/src/passes/well_formed.rs, calyx/src/utils/namegenerator.rs, tests/errors/reserved-name.expect, tests/errors/reserved-name.futil
The frontend was parsing `reg = std_reg(32)` as `reg0` because of the
namegenerator. This changes the frontend so that reserved names are
parsed as is
=> Parse reserved names as is to generate error msgs

interp/Cargo.toml, interp/src/configuration.rs, interp/src/lib.rs, interp/src/logging.rs, interp/src/macros.rs, interp/src/main.rs, interp/src/primitives/combinational.rs, interp/src/primitives/stateful.rs, interp/src/structures/stk_env.rs
Another simple quality of life PR which revamps the logging infrastructure to use `slog` instead of `log`. The most salient difference is that any logging message coming from a primitive will have the source of the primitive included by default, rather than needing to specially format the message to contain it.
```
Dec 01 17:29:17.708 WARN Computation over/underflow: -78056.9766248 to -12520.9766387, source: main.e.pow1.mul
Dec 01 17:29:17.710 WARN Computation over/underflow: 85627.1313813 to 20091.1313781, source: main.e.pow1.mul
```
=> [Interpreter] Logging rework with Slog

calyx/src/passes/simplify_guards.rs, interp/Cargo.toml, interp/src/configuration.rs, interp/src/debugger/commands.rs, interp/src/errors.rs, interp/src/primitives/stateful.rs
Teeny PR which fixes a few typos in the CIDR help message and adds the name of the memory to the memory out of bounds index error.
=> [Interpreter/CIDR] Fix help typos and improve error message

calyx/src/analysis/reaching_defns.rs, calyx/src/ir/builder.rs, calyx/src/ir/mod.rs, calyx/src/ir/printer.rs, calyx/src/ir/rewriter.rs, calyx/src/passes/register_unsharing.rs, calyx/src/passes/sharing_components.rs, calyx/src/passes/top_down_compile_control.rs, interp/src/utils.rs, src/backend/mlir.rs, src/cmdline.rs, src/main.rs, tests/errors/insufficient-params.expect, tests/errors/mismatch-widths.expect, web/rust/src/lib.rs
Separate out the rewrite methods defined on `ir::Builder` into a new struct add more rewrite methods that are generally useful when working with passes that modify/rename parts of components.
=> Define `ir::Rewriter`

frontends/systolic-lang/gen-systolic.py, tests/frontend/systolic/array-1.expect, tests/frontend/systolic/array-2.expect, tests/frontend/systolic/array-3.expect
Mostly for convenience of simulation with the symbolic evaluator and because I didn't see a good reason to keep the output to be two dimensional.
=> Make systolic array output one dimensional

calyx/src/ir/from_ast.rs, calyx/src/ir/guard.rs, calyx/src/ir/mod.rs, calyx/src/ir/printer.rs, calyx/src/passes/lower_guards.rs, calyx/src/passes/simplify_guards.rs, interp/src/structures/environment.rs, src/backend/verilog.rs
Unifies the various guard comparison variants like, `ir::Guard::Eq`, `ir::Guard::Leq`, into a single variant `ir::Guard::CompOp` which takes another enum `ir::PortComp` to describe which comparison to perform. Simplifies a bunch of code that often has to do the same thing for all the comparison operations anyways.
=> Merge guard comparison variants into one variant

fud/icarus/icarus.py, fud/icarus/tb.sv, src/backend/verilog.rs, tests/backend/verilog/memory-with-external-attribute.expect
Also fixes #769.
With the runtime error test, we get:
```
% fud e tests/errors/runtime/multiple-drivers.futil --to dat --through icarus-verilog
✖ icarus-verilog → dat
`/var/folders/2c/3km1m01x2dgf3x4d3vfmvsl80000gn/T/tmppg5f4m5z/main.vvp +DATA=/var/folders/2c/3km1m01x2dgf3x4d3vfmvsl80000gn/T/tmppg5f4m5z +CYCLE_LIMIT=500000000 +OUT=/var/folders/2c/3km1m01x2dgf3x4d3vfmvsl80000gn/T/tmppg5f4m5z/output.vcd +NOTRACE=1' failed:
=====STDERR=====
=====STDOUT=====
DATA (path to meminit files): /var/folders/2c/3km1m01x2dgf3x4d3vfmvsl80000gn/T/tmppg5f4m5z
cycle limit set to   500000000
VCD tracing disabled
FATAL: /var/folders/2c/3km1m01x2dgf3x4d3vfmvsl80000gn/T/tmphylbw8x5:484: Multiple assignment to port `fsm.in'.
Time: 0 Scope: TOP.main
```
=> Enable multi-driver checking in Icarus backend

calyx/src/analysis/read_write_set.rs, calyx/src/analysis/schedule_conflicts.rs, calyx/src/ir/context.rs, calyx/src/ir/mod.rs, calyx/src/ir/structure.rs
Defines the `ReadWriteSet::port_reads` method and remove unnecessary uses of wrapped Iterators (`CellIterator` and `SigIter`). In general, iterators only need to be wrapped when the method may return multiple iterators in different branches. Otherwise, we should just return `impl Iterator` so that the compiler can inline the use of the Iterator.
=> [NFC] Refactor `analysis::ReadWriteSet`

docs/fud/synthesis.md, fud/fud/config.py, fud/fud/errors.py, fud/fud/stages/remote_context.py, fud/fud/stages/xilinx/emulation.py, fud/fud/stages/xilinx/xclbin.py
This is one more smaller-scale PR that depends on on #850 and #851 (and should not be reviewed until those are merged).
The gist is basically the same thing as #850, but for the fud stage in `emulation.py`. This is the stage that compiles a host C++ program as a testbench to run the compiled emulation "bitstream" from the `xclbin` stage. It previously also required SSH and did so with copied-n-pasted SSH functionality; this does even more refactoring to our SSH utilities to make them generic enough to cover this stage as well. I also added a `LocalSandbox` utility that both stages can share to make it easy to run identical functionality either locally or remotely, depending on the configuration.
This also extends the documentation to describe how to use this new emulation stage. …
=> [fud] Make SSH optional in Xilinx emulation stage

docs/fud/synthesis.md, fud/bitstream/gen_xo.tcl, fud/fud/stages/xilinx/xclbin.py
The first step in using the Xilinx toolchain is to package our Verilog code in a format called `.xo`. Vivado (via Tcl) appears to be the only way to do this. We have a script, `gen_xo.tcl`, that is derived from the Xilinx tutorial examples that does this packaging.
In an effort to understand what is actually going on, I tried simplifying and commenting this file. I tried to delete anything that looked unnecessary while confirming experimentally that this didn't break anything. This is a painful process, however, because running the compiler takes 5-6 minutes per execution. So there may still yet be unnecessary steps in this Tcl file. (Continuing to delete stuff could be a "fun" project for anyone who's interested, such as @yn224.)
I also wrote a narrative description of how I believe …
=> [fud] Simplify & document .xo production

fud/fud/errors.py, fud/fud/exec.py, fud/fud/registry.py
A bandage solution to the problem in https://github.com/cucapra/calyx/issues/867. Assumes that the file discovery stuff is defined in stage configuration and uses the registry to find the states that the given may generate. The logic is gnarly which is sad.
=> Discover states instead of stages using filenames

calyx/src/default_passes.rs, calyx/src/ir/structure.rs, calyx/src/passes/comb_prop.rs, calyx/src/passes/mod.rs, tests/passes/comb-prop.expect, tests/passes/comb-prop.futil
Implements one of the two passes mentioned in https://github.com/cucapra/calyx/issues/869. See test file to see how this works. The only interesting thing is that it needs to propagate writes through wires (`w1` and `w2` are wires):
```
w1. in = c;
w2.in = w1.out;
r.in = w2.out;
```
into:
```
w1.in = c;
w2.in = c;
r.in = c;
```
This pass does not eliminate unused assignments. A different pass will be responsible for that.
=> Combinational Propagation pass

calyx/src/analysis/dataflow_order.rs, calyx/src/analysis/graph.rs, calyx/src/ir/from_ast.rs, calyx/src/ir/mod.rs, calyx/src/ir/rewriter.rs, calyx/src/ir/structure.rs, calyx/src/passes/comb_prop.rs, calyx/src/passes/component_iniliner.rs, calyx/src/passes/hole_inliner.rs, calyx/src/passes/merge_assign.rs, calyx/src/passes/register_unsharing.rs, calyx/src/passes/remove_comb_groups.rs, calyx/src/passes/sharing_components.rs, calyx/src/passes/well_formed.rs, interp/src/structures/environment.rs, src/backend/verilog.rs
Defining this struct enables a future opportunity to use Rc instead of cloning Id everywhere. Canonical representation of ports are pervasively used in the compiler so it should be cheaper to use them.
=> Define `ir::Canonical` for port's canonical representation

docs/fud/xilinx.md, docs/intro.md
@sampsyo seems like people keep into problems with the `opencl` dependency for `fud`. We should probably just not have them install it when getting started. Can you confirm that this is the right way to tell `flit` to skip optional dependencies?
=> [docs] do not install all `fud` dependencies

calyx/src/analysis/control_order.rs, calyx/src/analysis/mod.rs, calyx/src/analysis/read_write_set.rs, calyx/src/ir/printer.rs, calyx/src/passes/par_to_seq.rs, fud/fud/stages/interpreter.py, tests/passes/par-to-seq/ignore-this-comp.expect, tests/passes/par-to-seq/ignore-this-comp.futil, tests/passes/par-to-seq/no-order.expect, tests/passes/par-to-seq/no-order.futil, tests/passes/par-to-seq/reorder.expect, tests/passes/par-to-seq/reorder.futil
Make `par-to-seq` sort control programs in a way that they are correct wrt to dataflow dependencies
=> Implement ControlOrder analysis

primitives/binary_operators.sv
The previous implementation would take 4 cycles and started breaking when we implement static compilation in #909.
=> multiplier implementation should take 3 cycles

Cargo.lock, interp/Cargo.toml, interp/src/configuration.rs, interp/src/debugger/cidr.rs, interp/src/interpreter/group_interpreter.rs, interp/src/lib.rs, interp/src/logging.rs, interp/src/macros.rs, interp/src/main.rs, interp/src/primitives/combinational.rs, interp/src/primitives/stateful.rs, interp/src/structures/environment.rs, interp/src/structures/stk_env.rs, interp/src/tests/primitives.rs
Sorry for the eclectic PR, kinda kept jumping from one thing to another on this one. This takes care of a few things that have been on the back of my todo list for a while:
- removes the outmoded `-p` flag from the debugger
- Remove the global config struct and weave the configuration options through the appropriate calls
- Update the root logger to feature an explicit initiation call and replace use of `lazy_static` with `once_cell` to make the deferred initialization easier
- Add an overflow warning to the `StdFpAdd` and `StdFpSub` primitives. Not sure why this was missing in the first place.
- Added a `ConfigBuilder` struct to make putting together the configuration a little nicer. It's not really necessary for anything but it does make me happy, so there's that at least.
This also …
=> [Interpreter] Change-based-sim and misc feature round-up

calyx/src/frontend/parser.rs, calyx/src/ir/attribute.rs, tests/errors/multiple-attr-vals.expect, tests/errors/multiple-attr-vals.futil
The attribute structure only support String -> u64 mapping. Previously, if multiple values are provided for the same key, the compiler would silently select the last one. Now, this is an error.
=> Error if multiple values for an attribute provided

fud/fud/config.py, fud/fud/main.py, fud/fud/registry.py
Fixes the problem with `fud` inferring the wrong state for output files. The inference function was always returning the source of a stage. #867 remains the actual underlying problem here---there is no clear meaning with associating file extensions to stages, which represent transformation from one state to another. The ideal solution would tie file extensions to particular states instead.
=> fud state inference for targets

docs/fud/xilinx.md, tests/xilinx/runt.toml
In light of the problems in #867 and #946, the only way to make .xclbin generation work in fud is to combine *both* `-o foo.xclbin` *and* `--to xclbin`. This makes the relevant test do exactly that. It also changes the docs to similarly recommend `--to xclbin`.
(As a quick reminder, the reason we can't do `--to xclbin` by itself is that fud doesn't yet support binary output on stdout. So we must produce a file instead.)
/cc @yn224, who may be interested in this as a way to resolve #888.
=> Fix the Xilinx tests to work with recent fud

interp/src/primitives/stateful.rs, interp/src/structures/environment.rs, interp/src/tests/primitives.rs, primitives/binary_operators.sv, primitives/math.sv
Small PR which closes #584 and (hopefully) fixes some discrepancies with the reset signal behavior in the verilog primitives.
=> [Interpreter / Calyx Comp] Fix the reset signals

calyx/src/passes/well_formed.rs
`well-formed` has a long known issue where it doesn't consider groups whose `go` signal is being used as "used" and throws an error. This PR fixes this.
=> well formed considers structurally used groups

interp/src/debugger/cidr.rs, interp/src/debugger/name_tree.rs, interp/src/structures/names.rs
Small PR which changes the current implementation of cider's `where` (alias `pc`) command to output the set of active leaf nodes in the program as a first step towards a source level translation. This also sets up the minimal serde infrastructure required to serialize this as a json.
Currently invoke nodes are included with angle braces denoting that they correspond to a nameless "phantom" group. We'll likely want to change this placeholder once we have a better sense of the interface we want to expose.
=> [Interpreter/Cider] Output set of active leaf nodes

interp/src/debugger/cidr.rs, interp/src/debugger/commands.rs, interp/src/debugger/name_tree.rs, interp/src/debugger/parser/command_parser.rs, interp/src/debugger/parser/commands.pest, interp/src/interpreter/control_interpreter.rs, interp/src/structures/names.rs
Keeping with the conversation yesterday, the `pc` command now outputs the set of active (pos_tag, instance_name) pairs. It does not currently include any of the leaf nodes which lack a `pos` annotation. This means the interpreter side of the source position approach is mostly complete. 
As an afterthought, we may wish to support multiple position annotations if we find the idea of source tracking through multiple translation layers worthwhile. (TVM -> Dahlia -> Calyx)
Also added an optional numerical argument for the step command so `s 5` now performs step five times. This is mostly as a convenience (for me, primarily).
=> [Cider] Update the active set output to include pos tags

.github/workflows/rust.yml
Recent [changes to a dependency of black formatter](https://github.com/psf/black/issues/2964) broke our CI for python formatting. Hopefully this switch will fix it.
=> Switch to official black format GA

fud/fud/exec.py, runt.toml
`fud` couldn't read from input streams. This PR changes some checking logic to make sure it can.
=> fud can accept streams as input

calyx/src/default_passes.rs, calyx/src/passes/wire_inliner.rs, tests/passes/wire-inliner.expect, tests/passes/wire-inliner.futil
`hole-inliner` relied on the `compenent-interface-inserter` pass to assign to the `go` and `done` conditions for each component (this seems like an odd choice and I don't remember why we do it this way). `wire-inliner` no longer requires this.
=> wire-inliner: do not compile when control program is empty

frontends/relay/relay_visitor.py, interp/src/debugger/cidr.rs, interp/src/debugger/mod.rs, interp/src/debugger/source/metadata.pest, interp/src/debugger/source/metadata_parser.rs, interp/src/debugger/source/mod.rs, interp/src/debugger/source/structures.rs, interp/src/errors.rs, interp/src/main.rs
Replaces the sedre-based json source map parsing with a custom pest parser. This updates the relay code to match the format change.
Example metadata file:
```
0: "let %x: Tensor[(1, 20, 24, 24), float32] = nn.conv2d(%data, %conv1_w, padding=[0, 0, 0, 0], kernel_size=[5, 5]) /* ty=Tensor[(1, 20, 24, 24), float32] */;"
1: ""
2: "let %x2: Tensor[(1, 20, 12, 12), float32] = nn.max_pool2d(%x1, pool_size=[2, 2], strides=[2, 2], padding=[0, 0, 1, 1]) /* ty=Tensor[(1, 20, 12, 12), float32] */;"
3: "let %x3: Tensor[(1, 50, 8, 8), float32] = nn.conv2d(%x2, %conv2_w, padding=[0, 0, 0, 0], kernel_size=[5, 5]) /* ty=Tensor[(1, 50, 8, 8), float32] */;"
4: "let %x4: Tensor[(1, 50, 8, 8), float32] = nn.bias_add(%x3, %conv2_b) /* ty=Tensor[(1, 50, 8, 8), float32] */;"
5: "let %x5: Tensor[(1, 50, 4, 4), …
```
=> [Cider] Overhaul source parsing

calyx/src/passes/well_formed.rs
Fixes the confusing error message Pai ran into.
=> better error message when the group uses static=0 annotation

Cargo.lock, calyx/src/pass_manager.rs, web/rust/Cargo.toml, web/rust/src/lib.rs
=> Fixes for the Playground

calyx-py/calyx/py_ast.py, calyx/src/frontend/ast.rs, calyx/src/frontend/parser.rs, calyx/src/frontend/syntax.pest, calyx/src/frontend/workspace.rs, calyx/src/ir/context.rs, calyx/src/ir/from_ast.rs, calyx/src/ir/printer.rs, frontends/relay/relay_visitor.py, frontends/systolic-lang/gen-systolic.py, interp/src/debugger/source/metadata.pest, interp/src/debugger/source/structures.rs, interp/src/main.rs, src/main.rs, tests/parsing/metadata.expect
This implements the proposal in #994, the only major difference with the described minimum proposal is that this uses `#{` and `}#` as the delimiting characters, rather than `{` and `}` as the latter are likely to appear in source positions.
This means that the metadata now appears at the end of the file like:
```
...
METADATA #{ 
// Some stuff
}#
```
On the IR side the stuff between the brackets is treated as an opaque string so it only gets parsed as the metadata source map when given to Cider.
The main benefit is that this simplifies the user calls, so that the following now suffices to pass source position from the frontends
```
fud e --to debugger tests/frontend/systolic/array-3.systolic -s systolic.flags "--write-metadata " -q
```
```
fud e --to debugger lenet.relay -s relay.flags …
```
=> [Calyx/Cider + Frontends] Metadata rewrite

fud/fud/exec.py, fud/fud/executor.py, fud/fud/stages/xilinx/xclbin.py
Fixes the problem with `fud` spinner when using `--to debugger`.
=> Disable terminal spinner for Terminal states like --to debugger

interp/src/debugger/cidr.rs, interp/src/debugger/context.rs, interp/src/debugger/name_tree.rs, interp/src/interpreter/control_interpreter.rs, interp/src/interpreter/group_interpreter.rs, interp/src/main.rs, interp/src/structures/names.rs
Fixes a bug with the position tag extraction for group enables which closes the loop on Dahlia source position. Also cleans up some of the code around managing breakpoints and adds better feedback for those commands. Changes the way cider processes EOFs, so that it will be possible to build a runt test suite for the debugger behavior.
=> [Cider] Some UX fixes and patching cider-side dahlia source bug

interp/src/debugger/cidr.rs, interp/src/interpreter/component_interpreter.rs, interp/src/interpreter/control_interpreter.rs, interp/src/interpreter/interpreter_trait.rs, interp/src/interpreter/mod.rs, interp/src/macros.rs, interp/src/primitives/combinational.rs, interp/src/primitives/mod.rs, interp/src/primitives/primitive.rs, interp/src/primitives/stateful.rs, interp/src/structures/environment.rs, interp/src/structures/mod.rs, interp/src/structures/state_views.rs, interp/src/structures/stk_env.rs, interp/src/structures/values.rs, interp/src/tests/stk_env.rs
A whole bunch of documentation improvements for the interpreter with some mild refactoring.
Moves the stateviews into their own file and removes the useless `State` trait which was not actually doing anything.
Renames `Smoosher` to `StackMap` but retains `Smoosher` as an alias.
Fixes a few typos here and there.
This is far from exhaustive, there will be more documentation passes in the proximate future
=> [Interpreter] Checkpoint for improving docs

calyx/src/passes/canonical.rs, examples/futil/dot-product.expect, examples/futil/vectorized-add.expect, tests/passes/canonical/guard.expect
=> Disable canonicalization: `a = g ? 1` -> `a = g`

primitives/core.sv, tests/backend/verilog/big-const.expect, tests/backend/verilog/memory-with-external-attribute.expect
Add out of bounds checking to memory primitives for the verilator backend. Fixes #1004.
=> Add out of bounds checking to memory primitives

src/backend/verilog.rs, tests/backend/verilog/big-const.expect, tests/backend/verilog/memory-with-external-attribute.expect, tests/errors/multiple-done.expect, tests/errors/multiple-done.futil
Simple backend code generation changes that don't emit mux expressions when there is exactly one assignment. Also adds the missing test for multiple done conditions for #1014.
=> Backend cleanup

docs/fud/xilinx.md
Relevant to the overall #876 tracker, and more pertinently to #1019 as part of @nathanielnrn's work this summer.
This just adds some basic documentation of fud's `fpga` stage, which lets you actually run `xclbin` files, either in emulation or proper FPGA execution. Unfortunately, this requires setting a lot of annoying environment variables before you run fud; #872 should solve this. But for now, we have the bad-but-working way documented.
I also added a note to the existing documentation of the `wdb` stage that it may not be worth using. But I don't want to delete that yet because it may be our only way to get waveforms for now. (As a side note, it would be _really_ good if we had a way to convert from `wdb` waveform trace files to ordinary `vcd` files…)
=> Document fud's `fpga` Xilinx execution/emulation stage

fud/fud/config.py, fud/fud/stages/xilinx/emulation.py, fud/fud/stages/xilinx/execution.py
.wdb and .wcfg files can be created in `fud-out-<N>` directories by passing in `-s fpga.waveform true` as part of the fud invocation. Fud invocation must be `--to fpga` or go through the fpga stage.
Clean up doesn't currently work because of out of order operations.
(In practice, the `fud-out-<N>` directory is ~0.5 gigs due to a big hidden `.run/` directory. If I understand correctly this is an artifact of the debug mode required to output the files we want and can safely be deleted.)
=> Create flag option to create .wdb and .wcfg files

calyx/src/ir/structure.rs, calyx/src/passes/well_formed.rs, tests/errors/non-entrypoint-external.expect, tests/errors/non-entrypoint-external.futil, tests/passes/well-formed/ref-type-mismatch.expect
=> Disallow @external outside main

docs/fud/xilinx.md, fud/fud/config.py, fud/fud/stages/xilinx/execution.py
This is just a quick follow-up to @nathanielnrn's work in #1036! I wanted to add some documentation for the new option to save WDB files so we don't forget how to use this useful new functionality. While I was at it, I found it was easier to explain a slightly different version of the feature.
Namely, previously, the `fpga.waveform` fud option would have two effects: don't delete the temporary directory (like `save_temps` elsewhere), and ask XRT/xsim to produce a waveform trace. I think it's a little friendlier to keep these separate, even if just doing `fpga.waveform` by itself now is useless: it will create a WDB file and then immediately delete it! Hopefully this makes sense, and `fpga.save_temps` is useful for other purposes that might have to do with those temporary files.
Anyway, I …
=> [fpga] Docs & tweaks for saving WDB traces

fud/fud/check.py, fud/fud/config.py, fud/fud/stages/futil.py, fud/fud/stages/interpreter.py, fud/fud/stages/relay.py, fud/fud/stages/systolic.py, fud/fud/stages/verilator/stage.py, fud/fud/stages/vivado/stage.py, fud/fud/stages/xilinx/emulation.py, fud/fud/stages/xilinx/xclbin.py
Another PR will rename `futil_directory` to something like `base_directory`. This just centralizes the logic for `futil_directory` to the configuration itself of being a magic string.
=> define config.ROOT instead of magic "futil_directory" key

calyx/src/passes/compile_ref.rs, calyx/src/passes/dump_ports.rs, calyx/src/passes/externalize.rs, tests/passes/externalize.expect
Another weird problem with the cell interface inlining problem in #1034. In this case, the externalize pass used by the synthesis pipeline needs the `@clk` and `@reset` ports to be inlined in the main component interface because otherwise they are not usable.
This is different from `ref` cells because they occur in non-`main` components and can implicitly use the clk of the context.
=> dump ports should inline clk and reset after lowering

docs/fud/xilinx.md, fud/fud/stages/xilinx/execution.py
The Xilinx simulator produces WDB traces by default. We now can also produce VCD files, which may be more convenient to use. This makes the `-s fpga.waveform` config option produce both and documents where to find the resulting files.
The way this works is to add options like this to `xrt.ini`:
```
[Emulation]
debug_mode=batch
user_pre_sim_script=/scratch/adrian/pynq-ex/pre_sim.tcl
user_post_sim_script=/scratch/adrian/pynq-ex/post_sim.tcl
```
(Note the absolute paths! fud generates these itself, of course.) The `user_*_sim_script` options let you run arbitrary Tcl commands as part of the xsim simulation. `pre_sim.tcl` contains:
```tcl
open_vcd
log_vcd *
```
And `post_sim.tcl` just has:
```tcl
close_vcd
```
And that's all there is to it.
This may be of interest to @nathanielnrn to avoid …
=> [fud] FPGA stage produces VCD files when waveform is enabled

fud/fud/stages/xilinx/xclbin.py, src/backend/xilinx/xml.rs
Fixes #1080, which is part of #1072
=> Added --disable-init flag to fud xclbin stage

src/backend/xilinx/memory_axi.rs
Before, due to verilog order of operations addr offsets were incorrectly
adding before shifting.
Generated code now places shifted bits into a wire which is then added.
In the future, this commit could be reversed, depedent on the vast
library fixing this order of operations bug
=> Fix addr_offset logic

Cargo.lock, calyx/src/frontend/workspace.rs, calyx/src/ir/context.rs
If we have some like:
```
extern "primitives/core.sv" {
primitive std_add(in: 32) -> (out: 32);
}
extern "primitives/core.sv" {
primitive std_sub(in: 32) -> (out: 32);
}
component main() -> () {
cells {}
wires {}
control {}
}
```
This will ensure that we only add the `"primitives/core.sv"` file once in the generated verilog file.
=> Deduplicate `extern` based on the path

src/backend/xilinx/memory_axi.rs, src/backend/xilinx/xml.rs
Previously, data was always assigned to WDATA[31:0] (for 32-bit wide
data), with WSTRB being assigned accordingly. This caused dtaa to only
be written to the base address. Now, WDATA is shifted based on
data width for each write that is supposed to occur. WSTRB also changed
accordingly.
=> Fix WDATA and WSTRB alignment issues

docs/lang/memories-by-reference.md
=> `refernece` -> `reference`

Cargo.lock, fud/fud/config.py, interp/Cargo.toml, interp/src/debugger/cidr.rs, interp/src/debugger/commands.rs, interp/src/debugger/io_utils.rs, interp/src/debugger/parser/command_parser.rs, interp/src/debugger/parser/commands.pest
Nothing too excited, mostly just some stuff I cooked up in between illness induced naps. This is just clearing out a few smaller things from my backlog:
- add `raw` flag to fud's defaults for the interpreter
- make `print-state` fall back to printing out all the ports on a cell when given a cell without internal state, rather than giving an error message
- replaced some of the backend for Cider's help messages. It is horribly over-engineered and includes phantom types but I am allowed those once in a while as a treat. I think it is marginally easier to maintain.
- introduced a new `explain` command which shows snippets for Cider's commands which take arguments
Unless told otherwise I am going to consider this a closure of #1133, per the change to fud's default behavior.
=> [CIDR] Misc tweaks & help message changes

src/backend/verilog.rs, tests/backend/verilog/big-const.expect, tests/backend/verilog/memory-with-external-attribute.expect
Add `COMPONENT START/END: <name>` markers within generated verilog modules. This is giant hack but sometimes we need a way to splice some verilog code into a module for simulation purposes.
Specifically, COCOTB waveform generation requires the main module to have some extra code.
=> Add markers at the start and end of the component

calyx/src/analysis/domination_analysis/dominator_map.rs, calyx/src/analysis/domination_analysis/node_analysis.rs, calyx/src/passes/infer_share.rs, docs/SUMMARY.md, frontends/relay/relay_utils.py, frontends/relay/relay_visitor.py, tests/frontend/relay/duplicate-relay-call.expect, tests/passes/domination-map/nested-seq.expect, tests/passes/domination-map/nested-seq.futil, tests/passes/infer-share-pass/uses_ref.expect, tests/passes/infer-share-pass/uses_ref.futil
Currently, TVM generated Calyx files do not share any components. 
We think this is for two reasons: 
1. Previously Calyx components with ref cells in them could not be shared. However, talking in the Calyx meeting, it seems like almost the exact opposite is true: ref cells, it seems, are never an impediment to sharing. (I've been thinking a bit about it by myself, and I think this is correct. If you think about it, ref-cells have the exact same behavior as passing a bunch of signals to the input/output ports of the component which we know will never be an impediment to sharing. This is because all of the "state" of ref cells are located outside the component they're used in. For example, if we have 2 instances of a component `c1` and `c2` that use ref cells and have a std_mem `mem` that …
=> Make TVM-to-Calyx files share components

src/backend/verilog.rs, tests/backend/verilog/big-const.expect, tests/backend/verilog/memory-with-external-attribute.expect
If verilog files did not end with a newline, the generated file would clobber together the first and last lines of two files.
=> Add newline b/w imported verilog files

calyx/src/passes/infer_static_timing.rs
With this change the polybench test that was failing is now compiling.
=> I think this might fix the polybench test that's failing?

fud/fud/main.py, fud/fud/stages/interpreter.py
A small PR from last week which adds an `interpreter-data` target to fud which just outputs the converted datafile for the interpreter. This is pretty much just for me, but in the future it might be worth thinking about if there are smoother ways to make it possible to keep intermediate files.
=> [FUD] Interpreter-data utility

fud/fud/stages/interpreter.py
A cute little bug that would erroneously cause the python deparse process to present values as negative when they should not be.
=> [Interpreter] Signed fix

Dockerfile
Set cocotb-bus to be installed directly from its [repo](https://github.com/cocotb/cocotb-bus) to fix a bug they have in published version.
Can confirm that this docker image built from this works out of the box on my machine for the cocotb runt tests. Unfortunately running _all_ of the runt tests was too much for my measly 8 GB of ram and froze my os (twice).
Only thing that might affect other tests should be the change of LANG env variable which is set to `utf-8` to make cocotb happy.
This should (finally! 🤞) allow #1153 to be merged
=> Fix Dockerfile not working with runt cocotb tests

calyx/src/analysis/graph_coloring.rs, calyx/src/passes/cell_share.rs, tests/passes/cell-share/bounded.expect, tests/passes/cell-share/bounded.futil
Gives more flexibility to the bound settings. 
(For example now we can not share combinational cells, share registers 5 times, and always share other components).
=> Small Changes to bounded sharing

fud/fud/stages/vivado/extract.py, fud/synth/synth.tcl, primitives/memories.sv
I kept the synth.tcl file the same, but left a comment in case anyone else wanted a bigger board while using havarti. Very few changes overall though.
=> Vivado Maps seq-mems to Urams

runt.toml
The static timing tests don't currently do anything meaningful because `top-down-st` is disabled by default anyways. We can re-enable them once `top-down-st` is fixed.
=> Disable unused static timing tests

calyx/src/analysis/domination_analysis/dominator_map.rs, calyx/src/passes/cell_share.rs, calyx/src/passes/papercut.rs, interp/src/structures/state_views.rs, src/cmdline.rs, tests/errors/papercut/read-missing-write-comb.expect, tests/errors/papercut/read-missing-write-comb.futil
=> Check read and write specs in combinational groups

calyx/src/frontend/ast.rs, calyx/src/frontend/parser.rs, calyx/src/frontend/syntax.pest, calyx/src/ir/attribute.rs, calyx/src/ir/control.rs, calyx/src/ir/from_ast.rs, calyx/src/ir/printer.rs, calyx/src/ir/structure.rs, calyx/src/passes/compile_sync.rs, calyx/src/passes/group_to_invoke.rs, calyx/src/passes/remove_comb_groups.rs, calyx/src/passes/remove_ids.rs, calyx/src/passes/top_down_compile_control.rs, src/backend/mlir.rs, tests/parsing/empty.expect
Okay, this is an admittedly weird thing to do but: this PR adds the ability to parse *empty* control blocks when they have attributes.
For example, this can be parsed now:
```
control {
@sync; // <-- note the semicolon
}
```
The reason is that it gives us to experiment with "proto-keywords" like more easily. We currently have the philosophy of trying features out using attributes before we turn them into full blown keywords.
For example, the `@sync` keyword is an example. The current semantics is that for a program like this:
```
control {
@sync A; B;
}
```
The synchronization happens before A executes. This means that sometimes we have to write programs like this:
```
control {
if lt.out {
@sync no_op;
} else {
@sync A; B;
}
}
```
Where the `no_op` group doesn't do anything. With this …
=> Add ability to parse empty control with attributes

primitives/core.futil, primitives/core.sv, tests/backend/verilog/big-const.expect, tests/backend/verilog/data-instance.expect, tests/backend/verilog/memory-with-external-attribute.expect, tests/import/a.expect
I honestly don't know if this is useful enough to justify a stdlib addition, but I found during AOC Day 2 (cf https://github.com/cucapra/aoc2022-calyx/pull/2) that I wanted to concatenate together two signals into one (so I could use them in as a compound look-up table key). `std_cat` is a simple primitive that does this and only this. An alternative would be to use the existing `std_pad` followed by `std_or`, but this was a little more convenient.
Feedback welcome! And rejecting this as too fiddly and not useful enough is OK too!
=> Add `std_cat` concatenation primitive

calyx/src/analysis/port_interface.rs, calyx/src/errors.rs, calyx/src/frontend/parser.rs, calyx/src/ir/component.rs, calyx/src/ir/from_ast.rs, calyx/src/ir/id.rs, calyx/src/ir/primitives.rs, calyx/src/passes/papercut.rs, calyx/src/passes/synthesis_papercut.rs, calyx/src/passes/well_formed.rs, calyx/src/utils/namegenerator.rs, interp/src/debugger/parser/command_parser.rs, tests/errors/duplicate-cells.expect, tests/errors/mem-only-reads.expect, tests/errors/papercut/cell-and-group-conflict.expect, tests/errors/papercut/cell-as-group.expect, tests/errors/redefine-external.expect, tests/errors/reserved-name.expect, tests/passes/well-formed/constant-ref-cell.expect, tests/passes/well-formed/main-ref-cell.expect, tests/passes/well-formed/ref-incorrect-name.expect
- More perf hacking with string interner
- remove span information from `ir::Id`
=> Remove span information from `ir::Id`

calyx/src/errors.rs, calyx/src/passes/well_formed.rs, calyx/src/utils/position.rs, interp/tests/control/iteration/iter_mult.futil, interp/tests/control/iteration/while.futil, interp/tests/control/static/while_static.futil, tests/backend/mlir/no-guards.expect, tests/backend/mlir/no-guards.futil, tests/backend/mlir/with-guards.expect, tests/backend/mlir/with-guards.futil, tests/correctness/new_fsm.futil, tests/correctness/sync/sync-dot-product-opt.futil, tests/correctness/sync/sync-dot-product.futil, tests/correctness/while.futil, tests/errors/group-comb-conflict.expect, tests/errors/group-comb-conflict.futil, tests/errors/group-cont-assign-conflict.expect, tests/errors/if-cond-conflict.expect, tests/errors/if-cond-conflict.futil
This check enforces the well-formedness constraint for `with <comb-group>` syntax which allows the assignments in the combinational group to be active during the entirely of the body of the `if` or `while` using the `with` syntax.
=> Check combinational group assignments do not conflict with control program

docs/frontends/dahlia.md, docs/fud/index.md, docs/tutorial/language-tut.md
This PR fixes a few broken links in the Calyx documentation. It also amends 2 commands: 
In the Dahlia setup instructions, the build instructions call for `sbt install` to be run. But this isn't an sbt command! I think this is supposed to be `sbt compile`, which is the definition of `make install` in the MAKEFILE. 
In the fud installation instructions, it's not clear that the flit commands should be run inside the `fud` directory. I added a `cd fud` to the commands to ensure users are in the correct directory. 
Let me know if there are any questions/fixes to be made!
=> Amending links/commands

fud/fud/stages/futil.py, fud/icarus/icarus.py
A recent change in #1323 added a new requirement for `pre_install` methods on newly-registered fud stages. The "futil" (core Calyx compilation) stage in fud didn't have one. At first glance, this wouldn't seem to be a problem, because that's a built-in stage that you never need to register. However, attempting to register the Icarus stage now makes fud crash:
```
$ fud register icarus-verilog -p fud/icarus/icarus.py
Registering external script: icarus-verilog
[fud] ERROR: Failed to register `icarus-verilog': Stage futil missing `pre_install()` method. If the stage has no pre-installation steps, add the  following stub to the class:
@staticmethod
def pre_install():
pass
```
The error message incorrectly complains about the "futil" stage, but that of course is not the problem (the "futil" …
=> [fud] Add `pre_install` to FutilToIcarus stage

calyx/src/passes/top_down_compile_control.rs, tests/passes/tdcc/empty-exit.expect, tests/passes/tdcc/empty-exit.futil, tests/passes/tdcc/nested-while.expect, tests/passes/tdcc/nested-while.futil
`control_exits` in TDCC computes the predecessors of a control program and should correctly guard the exit edges from the `while` with the loop's exit condition.
=> Exit edges for while are guarded with loop exit condition

calyx/src/ir/macros.rs, calyx/src/passes/compile_empty.rs, calyx/src/passes/compile_sync.rs, calyx/src/passes/top_down_compile_control.rs, calyx/src/passes/top_down_static_timing.rs, calyx/src/passes/wire_inliner.rs
Because `build_assignments!` knows exactly how many assignments it is going to create a compile-time, we can return an array instead of a vec
=> `build_assignments!` returns an array instead of vec

docs/compiler-as-library.md, docs/compiler.md, docs/interpreter.md, docs/lang/attributes.md, docs/lang/data-format.md, docs/lang/memories-by-reference.md, docs/lang/multi-component.md, docs/lang/ref.md, docs/libraries/core.md, docs/tools/editor-highlighting.md, docs/tools/runt.md, docs/tutorial/language-tut.md, tools/vscode/README.md
Fixes some minor issues in the documentation: a few broken links, typos, and one non-compiling code example.
=> Miscellaneous fixes in docs

calyx/src/analysis/mod.rs, calyx/src/analysis/static_par_timing.rs, calyx/src/passes/cell_share.rs, tests/passes/cell-share/static-par.expect, tests/passes/cell-share/static-par.futil, tests/passes/par-timing-map/nested-par.expect, tests/passes/par-timing-map/nested-par.futil, tests/passes/par-timing-map/nested-while.expect, tests/passes/par-timing-map/nested-while.futil, tests/passes/par-timing-map/simple.expect, tests/passes/par-timing-map/simple.futil
Implements the idea in #1353. 
The key HashMap has the following structure: 
```
Maps Par ID -> (Map that maps Enable ID -> clock interval (i,j))
```
The intervals are relative to the start of the par block. 
Couple of points: 
1) I chose not to include invokes in this because they're not included in #1331. Although, if we wanted to, it shouldn't be too hard to add support for them in this analysis. 
2) If we have nested static pars (that merge-static-par pass doesn't deal with), like: 
```
@static par{
@static seq{
...
@static par{
@static A; 
...
}
...     
}
}
```
Then the enable A will appear in the hashmap relative to _both_  par blocks.
=> Static Par Timing Analysis 

calyx/src/analysis/static_par_timing.rs, calyx/src/passes/cell_share.rs, tests/passes/cell-share/calyx_2020.expect, tests/passes/cell-share/calyx_2020.futil, tests/passes/cell-share/static-par.futil
Added two new flags for cell-share pass. 
1) "calyx_2020" flag: runs cell sharing w/ Calyx 2020 settings, aka unlimited sharing of registers/combinational components, no sharing of anything else. This is mainly so that we can look at the improvement of sharing over time 
2) "share_static_par" flag: whether or not to share across static par blocks. Right now, we probably shouldn't, because tdst isn't applied in all cases, so we actually don't have the timing guarantees across par block that the static attribute tells us. But we would eventually want this to be defaulted to true.
=> Cell Share pass flags

calyx/src/ir/traversal/visitor.rs
A one-line change I noticed in passing. No need to use `drain` in this context as that will result in unnecessary allocations and iteration. The drained vec retains its capacity and the new collected vec will need the same capacity. Using `std::mem::take` should just be a pointer swap and avoids extra allocation since the default val is an empty vec.
=> use `std::mem::take` in the component order

.github/workflows/verification.yml
This workflow installs OCaml/opam/dune/required libraries and takes about 16 minutes to run, mostly due to Coq and Core taking forever to build. I have configured it to only run on the `vcalyx` branch, and all it does is check that our code builds! 
You can check out a workflow run [here](https://github.com/priyasrikumar/calyx/actions/runs/4338631661/jobs/7575460684) (excuse the string of sad commits).
=> Create a workflow for VCalyx

calyx/src/utils/out_file.rs
Closes #1370 , both for verilog and all other backends.
=> Use `BufWriter`

calyx/src/ir/context.rs, calyx/src/ir/flat_guard.rs, calyx/src/ir/mod.rs, runt.toml, src/backend/verilog.rs, src/cmdline.rs, src/main.rs, tests/backend/verilog/big-const.expect, tests/backend/verilog/data-instance.expect, tests/backend/verilog/memory-with-external-attribute.expect
Our discussion about Verilog generation times on Monday kinda hooked me a bit. We talked a little about how Calyx is mostly a "wide" language as opposed to a "deep" language, in the sense that its syntax is not very nested, with one big exception: guards. Guards are very much a "deep" part of the language; they are unbounded expression trees. "Deep" structures like this are bad for performance, and in particular they are connected to some of the bad performance in Verilog generation that we've been seeing in #1360.
We talked a bit about a *long-term* project to make the language more "wide" than "deep," which is essentially described in #1051 and which @EclecticGriffin is already beginning to address in #1183.
But after the conversation, it occurred to me that, in the very short term, we …
=> Flattened guard emission in the Verilog backend

calyx-opt/src/passes/comb_prop.rs, calyx-opt/src/passes/dead_cell_removal.rs, tests/passes/comb-prop/comb-prop.expect, tests/passes/comb-prop/inline-write.expect, tests/passes/comb-prop/multiple-reads-from-write.expect
- more debugging information from dead-cell-removal
- remove rewritten assignments before rewrite application
=> `comb-prop`: Remove assignments before applying rewrites

fud/fud/config.py, fud/fud/main.py
With the growing number of tools used in a `fud` pipeline, it can get unwieldy to write down long stage override commands. This PR adds a `--stage-config` that allows users to pass a TOML file to override the stage options. Instead of writing:
```
fud e --to dat -s verilog.data foo.json -s verilog.cycle_limit 4 --through icarus-verilog
```
The user can define a file:
```toml
[stages.verilog]
data = "foo.json"
cycle_limit = 4
```
And run it using:
```
fud e --to dat --stage-config conf.toml --through icarus-verilog
```
In the future, it would be nice to be able to specify the `--through` stuff in the configuration file as well. Closes #1264.
=> `fud` can accept argument file for stage configuration

calyx-py/calyx/builder.py, calyx-py/calyx/gen_exp.py, calyx-py/calyx/gen_ln.py, calyx-py/calyx/gen_msb.py, frontends/relay/dahlia_impl.py
Part of #1301. This includes a small bevy of minor bug-fixes to the builder including a few instances of mutable defaults being used (a particularly troublesome anti-pattern) and a lot of type annotation adjustments.
A few experiential notes:
- ran into lots of trouble with set literals for par composition as the ordering is non-deterministic and it requires the contents to be hashable which is not the case for the base ast nodes as `dataclass`es don't implement hash unless they are frozen. This means you can't use things like the `invoke` builder in a set. The ordering issue is not necessarily a problem for general use but creates issues for the runt tests so I had to hack around it in a bunch of cases. Given that, it may make more logistic sense to use a tuple for par comp instead of a …
=> [calyx-py] Translate `gen_exp.py` to use the new builder

fud/fud/main.py
Attempt to fix #1089 by simply disabling generation of `initial` blocks. Closes #1089.
=> Disable generation of initial blocks

calyx-opt/src/analysis/reaching_defns.rs, calyx-opt/src/passes/well_formed.rs
Couple Small Changes 
- Got rid of some code duplication in Reaching Defns 
- Well Formed's `obvious_conflicts` can now detect conflicts between regular and static assignments (we can do this bc we only consider conflicts if the guard is true)
=> Small Improvements for Reaching Definitions and Well Formed 

.github/workflows/rust.yml, calyx-py/pyproject.toml, frontends/mrxl/pyproject.toml
The main point here was to specify, in the metadata for MrXL, that it depends on the calyx-py library. This leads to a hopefully-helpful error if someone tries to install MrXL before installing calyx-py.
Along the way, I:
* Moved both `pyproject.toml` files to the modern (PEP 517 standard) format.
* Added a "package name" `calyx-ast` we can use to specify the dependency. `calyx-py` seems redundant, and [`calyx` is taken on PyPI](https://pypi.org/project/calyx/), so this was the next best thing and decently descriptive.
=> [mrxl, calyx-py]: Specify a dependency

frontends/mrxl/mrxl/gen_futil.py, frontends/mrxl/test/dot.mrxl, frontends/mrxl/test/dot.mrxl.data, frontends/mrxl/test/sum.mrxl, frontends/mrxl/test/sum.mrxl.data
MrXL already had the requirement that the answer of a `reduce` operation be stored in a register, not an array. The compiler `gen_futil.py` was already assuming this. It was banking the output cell trivially (just tagging on the suffix `_b0`).
This PR firms this up. It does away with that trivial banking and _requires_ that the output of a `reduce` go into a register. 
Compiling the program
```
input avec: int[16]
output out: int[16] 
out := reduce 1 (a, b <- avec) 0 { a + b }
```
will now fail, with the exception 
```
TypeError: The accumulator of a `reduce` operation is expected to be a register. Consider checking the declaration of variable `out`.
```
The following will work:
```
input avec: int[16]
output out: int
out := reduce 1 (a, b <- avec) 0 { a + b }
```
=> MrXL: `reduce` must go to register

calyx-py/calyx/builder.py, calyx-py/calyx/gen_exp.py, calyx-py/calyx/gen_ln.py
Small batch of changes to improve the builder.
- add a `sub_component` constructor for `ComponentBuilder` to create a cell instantiating a Calyx sub-comp
- add a `get_component` method to `Builder` to lookup `ComponentBuilder`'s by name
- extend the `invoke` constructor function to take `ref_*` arguments
- misc docstrings and type labels
Of these it's mostly the `invoke` thing that was needed by @anshumanmohan
=> [calyx-py] Minor builder extensions

calyx-py/calyx/builder.py
fixes an issue with the ref_constructor which was expecting `ExprBuilder` instead of `CellBuilder`
@anshumanmohan
=> [calyx-py] patch bug in invoke constructor

docs/tutorial/frontend-tut.md
We were linking to `builder_example.py` instead of linking to the builder documentation.
=> Tutorial: fix a stray link to repo instead of docs

docs/tutorial/frontend-tut.md, frontends/mrxl/mrxl/parse.py
This PR touches up the pointers near the end of the tutorial where we tell folks to extend MrXL.
1. Nixed the suggestion that they try to lift
> Every array in a MrXL program has the same length.
because it's not terribly interesting.
2. Nixed the suggestion that they try to lift
> We only support 32-bit integers and computations over them. 
because the solution to that gets into .data files, and we want them to be able to live in .mrxl.data land.
4. Nixed the suggestion that they try to add `filter`; we don't have time to think about a golden solution.
5. Massaged away language suggesting that some of this is warmup and some "the challenge". The warm-up is going to be something smaller altogether (CC @priyasrikumar) and these three challenges are all equal in our eyes. Although secretly …
=> MrXL: pointers for self-guided tasks

docs/fud/index.md, docs/intro.md
- Fixed frontend link in `fud` index
- `fud` config command reordered
- Updated the pip3 dist manually. Long term, we may want a fix for this that is self-sufficient?
=> minor doc fixes

calyx-opt/src/passes/discover_external.rs, tests/passes/discover-external.expect, tests/passes/discover-external.futil
Add the `strip-suffix` flag for the `discover-external` pass. To use:
```
calyx -p validate -p discover-external -p validate -x discover-external:default=16 -x discover-external:strip-suffix=_
```
=> Strip suffix in discover external

.github/workflows/depot.yml, README.md
We ran into timeouts trying to build ARM Docker images on GitHub Actions (cf #1512, for example). [Depot](https://depot.dev) looks like a good solution here: it is a CI service specifically for doing Docker builds, and aside from being faster than the Actions runners, it also natively supports ARM builds in addition to x86 ones. (It also has built-in support for building multiarch images.) I contacted the folks from Depot and they generously donated a sponsored account, so I'd like to try this out. (They asked us to add a badge to our README to acknowledge the donation; I've done this.)
This setup builds a new Docker image for the `:latest` tag on every push to `master`. I hope this (a) helps me debug the action to see if it works, and (b) provides a "cutting-edge" image for people who …
=> Try setting up Depot for Docker builds

fud/fud/stages/verilator/json_to_dat.py, fud/fud/stages/verilator/numeric_types.py
Small fixes for `fud`'s fixed-point conversion routines. Addresses the following issues:
- When `frac_width` is zero, the result has an extra zero inserted in the LSB position.
- On overflow, the number of required integer bits was being incorrectly reported. Moreover, the conversion failed for formats with zero integer bits.
=> Fixed-point conversion fixes

docs/tutorial/frontend-tut.md
- Install the docker container
- Recommend installing a specific version of the docker image instead of latest.
- Walkthrough "Building a Frontend for Calyx"
- Currently tells people how to install `calyx-py` and `mrxl`, but these are already installed in the docker container.
- The Calyx-based simulation command uses `--through verilator`. Should we be using `icarus-verilog` instead? 
- Explain why we might need different physical banks in the "`Decl` nodes" section. Put this explanation under a `<details>` tag.
- In "Compiling `map` operations", point the reader to the file where the unimplemented `my_map_impl` is defined so they can go work on it.
- Nit: replace `---` with `–`.
- "Further Steps"
- Point people to the primitives or `-` and `/`.
- Find and link and explainer about …
=> Dry run fixes

docs/intro.md
When running the tutorial inside our Docker, I am now having them run
- `runt -i 'core|mrxl'` 
- `fud check verilog jq mrxl interpreter`
If anyone sees a reason to check additional `fud` stages, speak now!
I have check that these do work cleanly inside the latest Docker image. I have not tested these in any other form of Calyx installation (crate or built-from-source).
Closes #1559.
=> Add further sanity checks to docker installation instructions

interp/src/flatten/flat_ir/base.rs, interp/src/flatten/flat_ir/cell_prototype.rs, interp/src/flatten/flat_ir/component.rs, interp/src/flatten/flat_ir/control/structures.rs, interp/src/flatten/flat_ir/control/translator.rs, interp/src/flatten/flat_ir/identifier.rs, interp/src/flatten/flat_ir/mod.rs, interp/src/flatten/structures/context.rs, interp/src/flatten/structures/environment.rs, interp/src/flatten/structures/index_trait.rs, interp/src/flatten/structures/printer.rs, interp/src/flatten/structures/sparse_map.rs
This was supposed to be a nice little change to add some documentation and invoke to the flat ir. That latter point proved more complicated than I would've liked.
The flat ir now flattens `invoke`s alongside everything else and can pretty print them (including ref cells). Also took the time to make the pretty printer process constant literals properly, rather than printing the `out` port of the generated constant cell.
The `impl_index` macro works a bit differently now to make it easier to add docstrings
=> [cider: flat-ir] Documentation pass + invoke

docs/tools/editor-highlighting.md
- `fuse-mode` is no longer the name for `futil-mode`
- Pure emacs doesn't have `highlight-mode`, list as prerequisite
- Clarification between pure & space emacs
=> Updates to emacs syntax highlighting instructions

interp/src/flatten/flat_ir/base.rs, interp/src/flatten/flat_ir/cell_prototype.rs, interp/src/flatten/flat_ir/control/translator.rs, interp/src/flatten/mod.rs, interp/src/flatten/primitives/builder.rs, interp/src/flatten/primitives/mod.rs, interp/src/flatten/primitives/prim_trait.rs, interp/src/flatten/structures/context.rs, interp/src/flatten/structures/environment.rs, interp/src/flatten/structures/index_trait.rs, interp/src/flatten/structures/indexed_map.rs, interp/src/flatten/structures/printer.rs, interp/src/flatten/structures/sparse_map.rs
Some stuff from the last week which creates the basic environment (all ports are zero and all ref cells/ports are None). Includes sanity checks that the local offset based definitions match the instantiated global offset from the appropriate offset base.
Reworked the `SparseMap` to iterate in insertion order and got a little clever with index ranges to avoid keeping a list of every key in order.
=> [cider/flat] Instantiate the beginning flat environment

interp/src/flatten/flat_ir/base.rs, interp/src/flatten/mod.rs, interp/src/flatten/structures/environment.rs, interp/src/flatten/structures/indexed_map.rs
A tiny PR with a simple pretty print for all the cells in the program environment. Currently only prints the ports on actual cells but descends the whole tree. For programs with heavy use of ref-cells this is not yet super useful, but a good start.
Nothing super exciting in this one, though there is a kinda overkill iterator chain at one point which was fun for me to write and probably not at all fun to read.
=> [cider/flat] Print the flat env port states

calyx-opt/src/default_passes.rs
Maybe we should just `wrap-main` at the very start of the compilation pipeline. Anyways, this should fix the problem that @andrewb1999 was running into.
=> `wrap-main` runs at the start of lowering

src/backend/xilinx/toplevel.rs
Once we deprecate these memories, we need to change the logic here to ensure that AXI controllers can use `seq_mem` instead (#1261)
=> Ensure that `@external` memories are `std_mem_d1`

docs/lang/ref.md, primitives/compile.futil
Just a tiny docs fix for #1611; some anchors didn't survive the transition to `compile.futil` from `core.futil`.
=> Tiny docs fix (fixes #1611)

Cargo.lock, Cargo.toml, calyx-frontend/Cargo.toml, calyx-frontend/src/attribute.rs, calyx-frontend/src/attributes.rs, calyx-frontend/src/common.rs, calyx-ir/Cargo.toml, calyx-ir/src/component.rs, calyx-ir/src/control.rs, calyx-ir/src/guard.rs, calyx-ir/src/lib.rs, calyx-ir/src/serializers.rs, calyx-ir/src/structure.rs, src/backend/mod.rs, src/backend/sexp.rs, src/cmdline.rs
We are parsing Calyx programs in S-expression form for VCalyx. This PR adds support for serialization using `serde` for all current Calyx features. To compile Calyx with serialization support, run `cargo build --features serialize`. To use the serialization backend, you can use `-b sexp`, i.e., `/target/debug/calyx -b sexp prog.futil`.
Would love to hear thoughts on the following: 
- Right now, the responsibility for adding serialization support for new language features falls on whoever adds them to the repository. Does this seem reasonable, and if not, what are some good alternatives?
- This is my first time working with Rust features and I'm not 100% sure I got the TOML files right. Please let me know if anything needs to be changed! 
- I added the file `calyx-ir/serializers.rs` to …
=> Adding an S-expression backend!

calyx-frontend/src/parser.rs, calyx-frontend/src/syntax.pest, tests/errors/parser/sig-missing-comma.expect, tests/errors/parser/sig-missing-comma.futil
@andrewb1999 ran into this in #1610. Some parsing magic to make the compiler at least a reasonable error message.
=> Better when comma is missing in signature

calyx-py/calyx/builder.py
As far as I can tell, the builder library does not yet expose a way for the user to create `seq_mem`s. This is a quick PR to allow that.
=> Builder: allow user to generate `seq_mem_d1`

calyx-py/calyx/builder.py, docs/lang/memories-by-reference.md
The builder library did not allow registers to be passed by reference, and the docs were a little unclear as to whether registers could be passed by reference. This PR fixes those two things, and thereby closes #1616
=> Builder: allow registers to be passed by reference

calyx-py/calyx/builder.py
It turns out that using `seq_mem` requires that the Calyx file import import `primitives/memories.futil`. The builder library now does this.
Thanks @andrewb1999!
=> Builder: `seq_mem` requires an additional import

calyx-opt/src/passes/compile_repeat.rs, tests/passes/compile-repeat/nested.expect, tests/passes/compile-repeat/nested.futil
`compile-repeat` should use `finish_repeat` and not `start_repeat`. 
Using `start_repeat` was causing nested repeats to not get compiled, since it was only compiling the outer repeat, and leaving the inner `repeat` uncompiled.
=> Fix Repeat Bug

calyx-py/calyx/builder.py
Turns out that, in #1622, I was inadvertently toggling with the `is_external` status, not the `is_ref` status. Now I pass False for `is_external` and actually obey the user's wish accurately.
=> Builder: registers by reference: patch

CHANGELOG.md, calyx-opt/src/analysis/control_ports.rs, calyx-opt/src/default_passes.rs, calyx-opt/src/passes/component_iniliner.rs, calyx-opt/src/passes/data_path_infer.rs, tests/passes/inliner/inline-ref.expect, tests/passes/inliner/inline-ref.futil
Enables `inliner` to inline programs instances with `ref` cells. The changes are straightforward since we can just add the `ref` cell bindings in the `CellRewriteMap` and have the rewriter handle rest of the complexity.
This also helps move the needle on #1649.
=> Support inlining `ref` cells

CHANGELOG.md, calyx-ir/src/structure.rs, calyx-opt/src/passes/comb_prop.rs, tests/passes/comb-prop/wire-dst-read.expect, tests/passes/comb-prop/wire-dst-read.futil
=> `comb-prop`: Disable rewrites when wire output is used

calyx-py/calyx/queue_call.py, calyx-py/test/correctness/fifo.py, calyx-py/test/correctness/pifo.py
The eDSL code for the three kinds of queues had a magic number: the capacity of the queues, set to 10 in the examples. This quick PR declares the value as a constant.
There was another magic constant, technically unrelated but coincidentally also set to 10: the number of spots in the user-facing answer memory. This is controlled not by the flavor of queue (`fifo.py`, `pifo.py`, or `pifo_tree.py`) but rather by the top-level runner generated using `queue_call.py`. This too has been clarified in this PR.
=> Queues: more magic numbers

docs/frontends/mrxl.md
This PR updates the MrXL [one-pager](https://docs.calyxir.org/frontends/mrxl.html), clarifying that the example up top cannot actually be compiled to Calyx. It also clarifies the pedagogical goal of the language and provides appropriate links to the frontend tutorial.
Closes #1594.
=> MrXL: Update one-pager

CHANGELOG.md, Cargo.toml, src/futil.rs
We've waited a couple of version to do this so hopefully people have transitioned to the `calyx` binary. The next major version of the compiler will not install the `futil` binary.
=> Remove the `futil` binary

calyx-py/calyx/builder.py, calyx-py/calyx/gen_exp.py, tests/frontend/exp/degree-2-unsigned.expect, tests/frontend/exp/degree-4-signed.expect, tests/frontend/exp/degree-4-unsigned.expect, tests/frontend/relay/softmax.expect
Just starting off the process of catching the clients of the eDSL up to the nice new features.
So far I've just caught one file up to speed, and I wanted to surface is so that we can see how the expect tests are breaking and what we want to do about it. In particular, I think the breaks at present are all "just" up to renaming of cells and groups. More broadly, we may want to talk about whether it even makes sense to expect-test the futil files, when in other examples we pipe the futil code directly to veri{something} without saving it in a txt file, and expect-test the output of veri{something}.
Once we agree on a plan, we can do more of this in other files, and/or see if there are other opportunities for cleanup.
One known oddity in the present eDSL examples is that groups are often …
=> Builder: catch up `gen_exp` to new features of eDSL

docs/compiler-as-library.md, src/build.rs
This installs the primitives in the folder specified by the `CALYX_PRIMITIVES_DIR` environment variable. If the variable is not set, we default to `$HOME/.calyx`. Not sure if this is the best place to install things but going with it for now.
=> Install primitives in global folder

CHANGELOG.md, calyx-ir/src/structure.rs, calyx-opt/src/analysis/variable_detection.rs, calyx-opt/src/passes/clk_insertion.rs, calyx-opt/src/passes/compile_invoke.rs, calyx-opt/src/passes/group_to_invoke.rs, calyx-opt/src/passes/hole_inliner.rs, calyx-opt/src/passes/reset_insertion.rs, interp/src/interpreter/control_interpreter.rs
Adds a new `Cell::find_with_unique_attr` method which is less error-prone because the pass must explicitly handle/propagate the error if multiple ports with an attribute are found.
=> Deprecate `Cell::find_with_attr`

interp/runt.toml, interp/src/interpreter/component_interpreter.rs
Closes #1694 
This is a little dubious but the short version of the problem is that the chains trick the interpreter into thinking that one of the sub-cells is running, this adjusts the check to avoid making changes when the sub-component interpreters have already been reset but are not currently being driven.
=> [Cider] Patch ref-cell bug

Dockerfile
Bumps the version of `runt` in the dockerfile. This doesn't change our current testing infrastructure which uses the `calyx:0.3.0` container. Once we release a new version of the code, we can bump the testing container which will allow for #1698 to be merged.
=> bump runt version

calyx-opt/src/passes/static_inliner.rs
When looking into systolic array resource usage, I realized that inlining: 
```
static if port {
// one cycle body
} 
```
Was generating a register to hold `port`'s value. If it is more than one cycle, we need this register, in case `port` changes during execution of the `body`. But we shouldn't generate this register if the body is one cycle, since we don't need this. This was generating a ton of unnecesary registers in the systolic array.
=> Improve Static Inline

calyx-opt/src/analysis/live_range_analysis.rs, calyx-opt/src/default_passes.rs, calyx-opt/src/passes/dead_cell_removal.rs, tests/passes/cell-share/empty-invoke.expect, tests/passes/cell-share/empty-invoke.futil, tests/passes/cell-share/inline.expect, tests/passes/cell-share/inline.futil, tests/passes/cell-share/ref-share.expect
This hopefully fixes two deficiencies with cell sharing:
- After inlining a component, it's often the case that wires are created that are later rendered dead by the `comb-prop` pass. However, the continuous writes to these wires don’t get cleaned up until after the cell sharing pass has run, which can prevent sharing of inlined cells (see [`inline.futil`](https://github.com/cucapra/calyx/blob/ed56f007407916d70cd61ccb64bcc7e296ad3492/tests/passes/cell-share/inline.futil) for an example). This PR changes the default pass plan to run `dead-cell-removal` after `comb-prop` and before `cell-share`. To make this ordering work, I attempted to add support for `ref` cells and static timing to `dead-cell-removal`.
- The live range analysis considers an invoked cell to be written to if its list of …
=> Share cells in more situations

calyx-py/test/correctness/piezo_pifotree.py, calyx-py/test/correctness/piezo_pifotree.yx, calyx-py/test/correctness/pifo.py
@calebmkim pointed out that the `stats` component could probably do away with its `report` flag since it just continuously outputs its counter values to its outports. This PR does this. Indeed, the eDSL and Calyx code is simpler.
=> [PIFO Tree]: Telemetry without a `report` flag

calyx-py/test/correctness/sdn.py
Silly thing: I discovered a place where was doing a `par` with only one arm.
=> SDN: remove unnecessary `par`

calyx-py/calyx/queue_data_gen.py
I have adjusted the synthetic data generation script a little, when run with the `--piezo` flag.
Before: 
It used to just randomly generate 100 commands, which were pushes or pops. This meant that overflow and underflow were totally possible. Even if you made the queue resistant to over/underflows (so that the show just went on until all 100 commands were done) we could end the program with packets still left in the queue. This was bad because:
- Failing by under/overflowing is actually quite _cheap_, so this compromised our "average cost per push" numbers, for example.
- Pushing something and then never popping it also leaves some questions when trying to find average costs.
After:
Now we generate commands with a little more care, making sure that we never have underflows or overflows, …
=> Piezo PIFO trees: More thoughtful data gen 

docs/fud/axi-gen.md
Noticed some awkwardness/vagueness and spelling mistakes [here](https://github.com/cucapra/calyx/blob/master/docs/fud/axi-gen.md). Made some quick fixes. Largely in the section in the beginning describing what each 3 files `kernel.xml`, `main.sv` and `toplevel.v` are responsible for
=> Fix some typos and rephrase some `axi-gen.md` documentation

.gitignore, .vscode/settings.json
As discussed on Slack a while back
Adds back the vscode settings with a default snippet to format rust on save within the project workspace thing. Please commit stuff to the file very sparingly and only if it is something that should impact everyone. Thx
=> Add back the vscode settings

calyx-ir/src/printer.rs, tests/passes/static-promotion/invoke.expect, tests/passes/static-promotion/multi-static.expect
This fixes a few mistakes in the pretty-printer for `static invoke` statements (#1795). Please note the tricky `}` before an `else` that is misleadingly identified in the diff.
It doesn't fix the `componentmain` "feature" described in https://github.com/cucapra/calyx/issues/1795#issuecomment-1839521239. 😄
=> Fix pretty-printing for static invokes (#1795)

Dockerfile
One way to fix the issues with the CI is just to bump the version of rust being used.
Alternatively `runt` can restrict what version of `colored` it uses to one that has an msrv of `1.69` via a cargo.lock? Not sure if that's good practice or not.
cc: @rachitnigam @sampsyo
=> [Docker] bump rust version number

docs/lang/ref.md
Based on a question I had yesterday. This was the first place I looked for info so thought I would add it
=> Add that in guards ports can be literals to docs

docs/frontends/systolic-array.md, frontends/systolic-lang/systolic_arg_parser.py
Renames the confusingly named `--static` CLI argument to `--fixed-dim`. @calebmkim this might break some of your evaluation scripts.
=> Update SA docs and command-line opts

calyx-backend/src/firrtl.rs, tests/backend/firrtl/basic-cell.expect, tests/backend/firrtl/primitive-cells.expect
I had a fault of omission in my previous primitive cell translation where the generated `extmodule` didn't list any of the input/output ports. I realized that the fix was pretty similar to the previous [lines 80-106](https://github.com/calyxir/calyx/compare/primitive-cell-bug-fix?expand=1#diff-f16e7b65190b7d8381dde2cf3ba8bbcfad0e1c985ef449ed647dde975b37abc0L80) so I extracted out that code into a function. I checked that the outputted FIRRTL files passed the FIRRTL to Verilog compiler, so this should be a fix!
Please let me know if there's anything I can improve here :) Thank you in advance!
=> [Calyx-FIRRTL] Primitive cell bug fix

calyx-backend/src/firrtl.rs, tests/backend/firrtl/and-or-not-guard.expect, tests/backend/firrtl/basic-cell.expect, tests/backend/firrtl/basic-guard.expect, tests/backend/firrtl/comparison-guard.expect, tests/backend/firrtl/or-guard.expect, tests/backend/firrtl/primitive-cells.expect, tests/backend/firrtl/two-or-guards.expect
I ran into a problem with my FIRRTL backend where both the FIRRTL compiler and ESSENT would squash (for lack of a better term) guarded assignments into a straightforward assignments. For example, the FIRRTL code:
```
done is invalid ; default initialization
when wrapper_early_reset_static_seq_done.out:
done <= UInt(1)
```
was compiled to the below Verilog:
```
assign done = 1'h1;
```
since there were no other assignments to `done` in the FIRRTL program. This caused the execution to finish in 0 cycles since `done` was always `1`.
So, I fixed my backend to insert an assignment to 0, so it would produce the below FIRRTL:
```
done is invalid ; default initialization
done <= UInt(0)
when wrapper_early_reset_static_seq_done.out:
done <= UInt(1)
```
This solves the problem, as the FIRRTL …
=> [Calyx-Firrtl] Fix undefined values bug by initializing to zero

calyx-opt/src/analysis/control_order.rs, calyx-opt/src/analysis/reaching_defns.rs, calyx-opt/src/analysis/read_write_set.rs, calyx-opt/src/passes/schedule_compaction.rs, tests/passes/schedule-compaction/continuous-compaction.expect, tests/passes/schedule-compaction/continuous-compaction.futil, tests/passes/schedule-compaction/continuous-no-compaction.expect, tests/passes/schedule-compaction/continuous-no-compaction.futil
Fix #1767. Adds analysis so that compaction accounts for continuous assignments.
The analysis here is conservative, since it essentially treats all the continuous assignment as one big "block". In other words, any time a group affects the continuous assignments, then it will depend on any previous groups that affect on continuous assignments too. For example say we have
```
seq {
A; // Affects continuous assignments
B; 
C; // Affects continuous assignments
D; 
E; // Affects continuous assignments
} 
``` 
Then we detect an `A->C->E` dependence, in addition to the existing dependencies we already find by analyzing the groups/control. 
When I say a group "affects" a continuous assignment, I mean that the group reads or writes to a cell that continuous assignments read or write from (except …
=> Compaction Accounts for Continuous Assignments 

yxi/axi-calyx/axi-combined-calyx.futil
Looking over the hardcoded implementation while creating the generator, I'm not sure how this worked in the first place.
`read_data_reg` is supposed to store the value of `RDATA` for use in a group later on in the control sequence.
making `read_data_reg.write_en` high with `is_rdy.out` seems like there would be a delay of a cycle between storing the data and receiving it, so `RDATA` would in theory be garbage.
To me it makes sense that this should be high with the handshake.
`read_data_reg.write_en = RVALID & is_rdy.out ? 1'b1;`
Going to merge this and leave this here for record keeping/for those interested to look over in case I'm missing something.
cc @sampsyo
=> Fix read channel read_data_reg write_en

calyx-py/calyx/builder.py, docs/builder/ref.md
Was messing around building AXI implementations in python and thought this could be nice. If there are downstream effects I'm not aware of please let me know and I'll try to address them or stop pursuing this if it doesn't seem worth it.
Previously we had to write things like
```
invoke_txn_count = invoke(txn_count, in_in=const(32,0))
```
This PR lets us write write the above as
```
invoke_txn_count = invoke(txn_count, in_in=0)
```
which is what I initially did before being surprised that it didn't work.
Not sure who has been taking charge of builder stuff so
cc @anshumanmohan @rachitnigam @sampsyo
=> Add support for using python builder `invoke` with integer literals

calyx-py/calyx/py_ast.py, tests/frontend/systolic/array-1.expect
Same thing as #1858 for equality and inequality. I think these were missed there.
Worth noting that this is somewhat of a "brute force" solution that does not attempt to minimize parentheses. Not sure if that is something worth pursuing at the moment?
cc @rachitnigam
=> Add parentheses around `==` and `!=` in builder

calyx-backend/src/backend_opt.rs, calyx-backend/src/lib.rs, calyx-backend/src/primitive_uses.rs, calyx-backend/src/primitives.rs, src/cmdline.rs
This PR contains a new backend that lists all of the unique instantiations of primitives within a program into a JSON file. This is necessary for my Calyx-FIRRTL efforts because FIRRTL does not support parameterization of modules, and therefore I have to generate individual FIRRTL modules that each correspond to a specific primitive instantiation in Calyx. This backend is the first step, and the produced JSON file will be processed by a script that I will write next. I'll also add fud2 support for this backend soon.
As a side note, this backend would also be similarly useful for the BTOR2-Cider efforts as described in #1845 under **Generation Scaffolding**.
This backend borrowed a lot of code from the Resource Estimation backend, which I'm very thankful for :slightly_smiling_face: 
Please …
=> Backend for listing instantiations of primitives

yxi/axi-calyx/axi-combined-calyx.futil, yxi/axi-calyx/axi-generator.py
See #1865.
This PR touches both the hardcoded calyx implementation as well as the generator.
Doing this PR has made me realize we should start making efforts to get rid of the hardcoded implementation as things will pretty easily drift out of sync otherwise. 
1. Renames `base_addr` and `curr_addr` to `curr_addr_axi` and `curr_addr_interal_mem` respectively
2. Asserts a few properties we expect from our yxi input. Namely widths being divisible by 8 and mem sizes being powers of 
3. Simplifies the `was_high` signals, see the issue for more details. This is the thing I'm most unsure of w.r.t the correctness of the implementation. This ended up deviating a bit from the talk @sampsyo and I had. If anyone takes a look at this part I'd be happy to hear any and all feedback/thoughts.
After this …
=> Clean up AXI generator channels

Cargo.lock, Cargo.toml, docs/SUMMARY.md, docs/running-calyx/fud2.md, fud2/Cargo.toml, fud2/data/gen_xo.tcl, fud2/data/get-ports.py, fud2/data/interp-dat.py, fud2/data/json-dat.py, fud2/data/primitives-for-firrtl.sv, fud2/data/tb.sv, fud2/data/xrt.ini, fud2/data/xrt_trace.ini, fud2/fake/Cargo.toml, fud2/fake/src/cli.rs, fud2/fake/src/config.rs, fud2/fake/src/driver.rs, fud2/fake/src/lib.rs, fud2/fake/src/run.rs, fud2/src/main.rs
This adds the code from https://github.com/sampsyo/fake/commit/8365aa3946d78076ad7c11a972fe2b3ff1a1c420. I also added some extremely basic documentation.
There is a lot more work to be done on fud2 before it is viable as a day-to-day tool. This PR is the first step in [my proposal for a migration plan](https://github.com/orgs/calyxir/discussions/1837#discussioncomment-8101678), i.e.:
1. open this PR and merge fud2 into the Calyx monorepo
2. open a bunch of issues to map out what needs to be done (including basic functionality in fake, lots of new capabilities to cover the ops fud already supports, and much more documentation)
3. slowly roll things forward guided by those issues and the ecosystem's demands
4. someday later, reassess what it would take to do a proper replacement
In that …
=> Initial fud2 import

fud2/fake/src/cli.rs, fud2/fake/src/config.rs
Similar to `fud c --edit` but does not support querying keys yet. Tagging @sampsyo for visibility.
=> [fud2] Add subcommand to edit configuration

docs/lang/multi-component.md
Old fud command containing flag --to vcd_json resulted in stack overflow error. Changed command to use flag --to vcd.
=> Docs: multicomponent tutorial fud command fix 

.github/workflows/docs.yml
Overlooked this during the reorg! Simple fix (`master` -> `main`)
=> Deploy docs on `main`

docs/running-calyx/fud2.md
=> Fix tiny typo for fud2 doc

.github/workflows/format.yml, Dockerfile, calyx-backend/src/firrtl.rs, calyx-opt/src/analysis/compute_static.rs, calyx-opt/src/analysis/inference_analysis.rs, calyx-opt/src/passes/cell_share.rs
Bumps the rust version to stable. Let me know if you want to pin a particular version, or if it's ok to just use the docker image `rust:latest` and the toolchain `stable`.
=> bump rust versions to stable

calyx-py/calyx/builder.py, calyx-py/calyx/py_ast.py, calyx-py/test/example.py, calyx-py/test/if.py, calyx-py/test/invoke.py, docs/builder/ref.md
Allows to add attributes to components within the builder. This is needed as part of our AXI-wrapper generator #1733
Something like:
```
my_comp = prog.component("my_comp")
my_comp.attribute("my_attr", 1)
```
will produce a component signature that looks like:
```
component my_comp<"my_attr"=1>(...) -> (...)
```
I added note of this in the reference doc. Didn't think this warranted changing/adding any [tests](https://github.com/calyxir/calyx/tree/main/calyx-py/test) but can do that if we want.
---
I made sure this works with a little snippet of python uses this, but didn't think it was warranted to go into the repo, included here for completeness:
```
from calyx.builder import Builder
def add_attr_check(prog):
my_comp = prog.component("my_component")
my_comp.attribute("attr1", 7) …
```
=> Add component attributes to builder

calyx-stdlib/src/primitives.rs, primitives/stallable.futil, primitives/stallable.sv
Create a file for stallable primitives and add a stallable multiplier. Stallable primitives are very similar to pipelined primitives but have to ability to stall if an input stall signal is set to 1. When stall is 1, the multiplier will hold all values in inner registers at their current state until the stall value returns to 0. These kinds of primitives are useful for stallable pipelines which can arise when dealing with input dependent dynamic behavior.
I'm adding this as a separate primitives file instead of just changing the pipelined primitives to add a stall signal because in most use cases of pipelined primitives we don't want this signal. It likely could be optimized away by RTL synthesis, but I don't want users to have to think about it if they don't have to.
=> Add stallable primitives

Cargo.lock, docs/running-calyx/fud2.md, fud2/Cargo.toml, fud2/fud-core/src/cli.rs, fud2/fud-core/src/exec/driver.rs, fud2/fud-core/src/run.rs, fud2/src/main.rs
As part of #1899 (see also #1878 for context), this change addresses fud2's need for external "resource" files. The idea is, in release builds of fud2, to embed all these files into the executable using [the `include_dir` crate](https://docs.rs/include_dir/latest/include_dir/). To get access to these files, Ninja builds "extract" the resource files by calling back into fud2. Specifically, there is a new `fud2 get-rsrc` subcommand that Ninja files invoke to obtain specific resource files.
For example, here are some excerpts from a simulation build (`fud2 lti.futil --to dat --through icarus -s sim.data=t.json -v -m emit`):
```ninja
build-tool = /Users/asampson/Documents/cu/research/calyx/target/debug/fud2
rule get-rsrc
command = $build-tool get-rsrc $out
```
Every build now includes the …
=> fud2: Embed resources in executable, in release mode

fud2/fud-core/src/cli.rs, fud2/fud-core/src/exec/driver.rs
Just a really small task from #1878! This new `fud2 list` command just prints a list of all the registered states and operations, in case you forget a name or whatever.
The current output is:
```
$ fud2 list
States:
verilog: .sv .v
calyx: .futil
dahlia: .fuse
mrxl: .mrxl
dat: .json
vcd: .vcd
sim: .exe
verilog-noverify: .sv
firrtl: .fir
primitive-uses-json: .json
debug:
xo: .xo
xclbin: .xclbin
Operations:
calyx-to-verilog: calyx -> verilog
dahlia-to-calyx: dahlia -> calyx
mrxl-to-calyx: mrxl -> calyx
simulate: sim -> dat
trace: sim -> vcd
calyx-noverify: calyx -> verilog-noverify
icarus: verilog-noverify -> sim
calyx-to-firrtl: calyx -> firrtl
firrtl: firrtl -> verilog
firrtl-noverify: firrtl -> verilog-noverify
primitive-uses: calyx -> primitive-uses-json
verilator: verilog -> sim
interp: …
```
=> [fud2] Add `list` subcommand

docs/running-calyx/fud2.md
This adds a new section to the fud2 docs describing the overall design philosophy and a few of the core concepts (states, operations, setups). Surely there is more to be said here, but as things get more detailed, they'll want to start appearing in the Rust API docs, so that's probably where I'll expand next.
Part of #1878.
=> [fud2] Write some design docs

calyx-backend/src/firrtl.rs, tests/backend/firrtl/and-or-not-guard.expect, tests/backend/firrtl/basic-cell.expect, tests/backend/firrtl/basic-guard.expect, tests/backend/firrtl/basic-program.expect, tests/backend/firrtl/comparison-guard.expect, tests/backend/firrtl/or-guard.expect, tests/backend/firrtl/primitive-cells.expect, tests/backend/firrtl/two-or-guards.expect
This should hopefully be a small PR! It contains changes to `firrtl.rs` and associated tests so that output ports are initialized to invalid and 0. (I ran into Calyx programs where externalized memories would never get written, causing the FIRRTL-to-Verilog compiler to complain that output ports that wrote to those memories were never initialized)
Please let me know if there's anything I can improve/fix here!
=> [Calyx-FIRRTL] Initialize output ports

fud2/tests/snapshots/tests__emit@calyx_debug.snap, fud2/tests/snapshots/tests__emit@calyx_icarus_dat.snap, fud2/tests/snapshots/tests__emit@calyx_icarus_vcd.snap, fud2/tests/snapshots/tests__emit@calyx_interp_dat.snap, fud2/tests/snapshots/tests__emit@calyx_verilator_dat.snap, fud2/tests/snapshots/tests__emit@calyx_verilator_vcd.snap, fud2/tests/snapshots/tests__emit@calyx_xrt-trace_vcd.snap, fud2/tests/snapshots/tests__emit@calyx_xrt_dat.snap, fud2/tests/snapshots/tests__emit@dahlia_calyx.snap, fud2/tests/snapshots/tests__emit@mrxl_calyx.snap, fud2/tests/tests.rs
A follow-up to #1954. And part of #1878.
Just adds a bunch more tests to fud2 using the setup I created recently. Now every op in fud2 is covered except for `primitive-uses`; this should probably be covered once we have a more complete FIRRTL pipeline in here that depends on it.
(Incidentally, I had to look around for code coverage tools for Rust. I found I liked [llvm-cov](https://github.com/taiki-e/cargo-llvm-cov) more than the more popular [tarpaulin](https://github.com/xd009642/tarpaulin). The main problem I had with the latter is that I couldn't filter out all the rest of the source files—so there was this giant list of source files with 0% coverage from the rest of the entire Calyx workspace. Surely there is a flag to just focus on one crate/subdirectory, but I couldn't find it? …
=> [fud2] Several more tests

calyx-ir/src/builder.rs
This should fix #1969, at least in the short term. There are still some limitations, so we cannot declare all arbitrary widths to be supported but this should at least unblock a few things.
=> a tiny patch for the width check

interp/src/flatten/structures/environment/assignments.rs, interp/src/flatten/structures/environment/env.rs, interp/src/flatten/structures/environment/program_counter.rs
This should close #1917. As discussed it adds an additional check for assignments from groups which confirm that the go signal is high and it also skips assignments to non-done ports when the done condition is high or undefined. To make this work with guarded assignments to done which rely on the zero undefined semantics, if we finish convergence and there are done ports which remain undefined we set them to zero and rerun/continue convergence.
I am not entirely satisfied with the way this currently removes finished groups as they are removed on the following cycle rather than after the cycle where the done condition goes back to low. This will create problems in situations down the line where we want to do converge-cycle-converge for debugging. But it should be okay for the moment.
I …
=> [Cider 2]  Fix extra cycle

calyx-ir/Cargo.toml
Previously, running `cargo build --features serialize` from `calyx-ir` did not build properly. It would only build properly from the root directory. This PR lets the above command build successfully. I imagine this is what we want?
cc @rachitnigam @EclecticGriffin just to make sure this is right.
=> Let calyx-ir build with `serialize` feature

.github/workflows/docs.yml, .github/workflows/format.yml, .github/workflows/fud2.yml, .github/workflows/rust.yml, .github/workflows/verification.yml
ref : https://github.com/calyxir/calyx/pull/1976#issuecomment-2005781427
As of now, most of CI workflows (expect fud2 tests) only work on push event, which is triggered in the context of repo where the branch is. So when I make any changes in my fork, and open a PR, it does not correctly run CI on PR, and the the  status checks that are required are always pending. see https://github.com/calyxir/calyx/pull/1976
This PR does following changes :
1. change most CI events to push and pull_request , so that PRs from fork  can have their CI properly run
2. use correct URL in the container based tests, so that when they run on forks, the checkout doesn't fail. As of now, it is hard-coded to this repo, but that fails when run on forks, as the commit done there is not present here, hence it fails. …
=> Update CI to run on fork-based PRs and use proper repo when checking out

docs/debug/cider.md, docs/debug/index.md, docs/frontends/mrxl.md, docs/frontends/ntt.md, docs/intro.md, docs/lang/data-format.md, docs/running-calyx/fud/axi-gen.md, docs/running-calyx/fud/circt.md, docs/running-calyx/fud/external.md, docs/running-calyx/fud/index.md, docs/running-calyx/fud2.md, docs/tools/index.md, docs/tutorial/frontend-tut.md, docs/tutorial/language-tut.md
Some of the hyperlinks to documentation about fud and the compiler frontends for Calyx were broken - hoping that this fixes most of them. 
I'm not sure if there's a template engine for Calyx's documentation that would resolve these issues automatically - if so, feel free to disregard this PR :smile:
=> Fix hyperlinks to documentation for fud/frontends

.github/workflows/rust.yml, web/data/config.json, web/data/passes.json, web/validate-data.js
closes #1737 
ref : https://github.com/calyxir/calyx/issues/1737#issuecomment-1986905609
Sorry it took a bit of time to get this up, got busy in other things...
This adds a node script which will validate that 
1. All passes listed in the passes.json are valid (cross checking with calyx pass-help o/p)
2. all example files that are in config.json are actually present
Currently parked the CI in rust.yaml, as I figured it would be better to run on each push, can move to other yaml as per suggestions.
Also instead of checking with master, the files are checked at local level, so that addition of new file or removal of existing file is correctly detected. I can also add a step to post a comment on PR if the validation fails, but might be overkill.
Once suggested changes are added, will remove …
=> Add playground config validation script and CI

primitives/binary_operators.futil, primitives/binary_operators.sv
Library primitive that takes a constant value as a parameter. The input is multiplied by the constant value. Useful for translating between memory ports with different dimensions.
=> Add a combinational constant multiplication primitive

calyx-py/calyx/builder.py, calyx-py/calyx/queue_call.py, calyx-py/test/correctness/arbiter_6.py, calyx-py/test/correctness/reduction_tree.py
Just spotted a few instances where we were requiring users to provide names for cells when they could easily be generated, and were requiring users to provide bitwidths when they could easily be inferred.
=> eDSL: Infer more widths, require fewer cell names

Dockerfile, frontends/mrxl/test/runt.toml, interp/runt.toml, runt.toml, tests/xilinx/runt.toml, tools/data_gen/runt.toml
`cargo install runt` provides `v0.4.1`, yet the configuration is requesting `0.4.0`.
=> Update Runt version.

primitives/pipelined.sv
For some unknown reason Vivado decides to do DSP inference before retiming so this change actually matters (what a great and stable piece of software). I've tried a lot of combinations of synthesis options and I can't get it to retime the multipliers correctly. This change increases the max frequency from 300 MHz to nearly 500 MHz.
=> Fix pipelined_mult frequency for Vivado

docs/lang/static.md
Just a quick PR to document the trick allows the user to define a blank static dummy group, and then use it for fine-grained control over the execution of parallel arms in lockstep.
=> Docs: Document dummy group delay trick for `static par` coordination

primitives/pipelined.futil, primitives/pipelined.sv
Initializing these registers changes what DSP structure this gets mapped to which harms frequency. This change should be fine because no program should rely on the output of the multiplier until 4 cycles after the first set of inputs is given.
=> Another change to pipelined_mult to improve QoR

primitives/pipelined.futil
This should prevent default zero generations and help frequency significantly.
=> Mark `pipelined_mult` inputs as `@data`

calyx-backend/src/verilog.rs, calyx-frontend/src/attribute.rs, calyx-opt/src/passes/dump_ports.rs, tests/passes/compile-invoke/invoke-ref.expect, tests/passes/compile-invoke/ref-chain.expect, tests/passes/compile-invoke/ref-invoke.expect, tests/passes/compile-invoke/ref.expect, tests/passes/compile-invoke/static-ref.expect, tests/passes/externalize.expect
@andrewb1999 does this solve #2012? Lmk if it doesn't. 
Here's why I think it wasn't working before: 
The problem was that, in order to have "default-to-zero behavior" we needed the cell _and_ the port to be marked as`@data`. However, when we externalize it, we _change the parent cell_. 
```
component main(@go go: 1, @clk clk: 1, @reset reset: 1) -> (@done done: 1) {
cells {
// out.write_data's parent is out, which is marked as @data
@external @data out = seq_mem_d1(32, 1, 1);
...
} 
// out_write_data's parent is now main which is not marked as @data 
component main(...@data out_write_data: 32....) { ... }
``` 
I made a pretty hacky solution: when we externalize a cell, we only add the `@data` attribute when the cell is `@data` as well. This way, when we're in the Verilog backend, if we …
=> `@data` carried over to external memories 

calyx-opt/src/passes/compile_invoke.rs
This is a really tiny change to force an ordering on the "inlined" ports when compiling `ref` cells, to address #2016.
Recall that compiling `ref` cells (which happens in `compile-invoke`, despite the name) involves creating ports in the "host" component to mirror those in the `ref` cell it contains. Those ports are created by an `ir::Rewriter`, which produces a `HashMap`, which is of course nondeterministic. The strategy here is to just take those randomly-ordered ports and sort them before we add them to the "host" component, yielding deterministic IR from this pass.
I don't know if this is the best way, but it is at least a way.
=> Probably fix #2016: Sort ports when compiling refs

docs/intro.md, docs/running-calyx/fud/index.md
#1719 makes `fud` depend on `calyx-py` (there used to be a dependency the other way, that PR switches the dependency). 
Either way, in the meantime we should update the docs to reflect this.
=> Update docs to note `fud` dependency on `calyx-py`

calyx-py/calyx/builder.py, calyx-py/calyx/gen_exp.py
Some methods were calling themselves "std_d1" when they were in fact expecting comb_mem_d1. This is a quick fix for that.
=> eDSL: Fix method names

calyx-py/calyx/builder.py, calyx-py/calyx/gen_msb.py
Following on from the work of #2034 and #2036, this PR does some tidying on the single file `gen_msb.py`. The diff file will be very pleasing, as this file was really ripe for a little cleanup using modern eDSL features. We now pass as few strings as we can, infer as many widths as we can, and generally leave all group-creation to the builder library.
Closes #1673
=> `gen_msb`: Tidying using modern eDSL

interp/src/flatten/structures/environment/env.rs, interp/src/flatten/structures/environment/program_counter.rs
Part of #1913.
Adds a simple lockstep version of par functionality via the auxiliary child-count map. The `step` function ends up being responsible for updates to the par state, rather than the program tree traversal. As a side effect, a node in the PC pointing to a par has two different meanings based on the state of the auxiliary map. If there is no entry in the map, then it means we are about to enter this par node. If there is an entry, it means that one of the threads of the par is about to exit. In this latter case, there may be multiple simultaneous copies of the entry if par threads exit simultaneously. I think this is a fine first approach though I worry it may cause some confusion in understanding the PC down the line for users of the debugger. If so, some fancier printing may …
=> [Cider 2] Barebones Par

docs/intro.md
Fud depends on calyx-py, and this fact is documented [here](https://docs.calyxir.org/#installing-the-command-line-driver). It is maybe a little terse and confusing.
> fud currently has a dependency on [calyx-py](https://docs.calyxir.org/builder/calyx-py.html), which you need to install first.
Someone who is quickly working through this page and copy-pasting every code block will miss it. This PR inlines the instructions to make the section more foolproof.
=> Docs: document `calyx-py` installation step more clearly

fud2/src/lib.rs, fud2/tests/snapshots/tests__emit@calyx_debug.snap, fud2/tests/snapshots/tests__emit@calyx_interp_dat.snap, interp/Cargo.toml, interp/src/flatten/structures/environment/env.rs, interp/src/flatten/structures/environment/program_counter.rs, tools/cider-data-converter/Cargo.toml
Part of #2044 which adds a basic fud2 flow for Cider 2, named `interp-flat`.
Also some minor tweaks to make the code a little nicer in a few places. I need to go implement `with` before I can get much of the test suite hooked up, since nearly all the test suite programs use it in some capacity
=> [Cider 2] Misc fixes + fud2 integration

docs/compiler.md
The [docs](https://docs.calyxir.org/compiler.html#controlling-passes) tell you to run 
```
cargo run -- --list-passes
```
from the root of the repository in order to see a list of Calyx passes. In reality I have found the command is 
```
calyx --list-passes
```
and it does not need to be run from the root. 
This PR changes the docs to reflect this. Please let me know if I've somehow gotten it wrong, or if additional context is needed at that point in the docs.
=> Docs: correct command to list passes

interp/src/flatten/primitives/builder.rs, interp/src/flatten/structures/environment/env.rs, interp/src/flatten/structures/environment/program_counter.rs, interp/src/serialization/data_dump.rs
Part of #1913.
This modifies the program counter to add support for `with` groups and continuous assignments. Nothing super fancy here.  The only annoying thing of note is that I had to reintroduce a `take`-style method to deal with the existing structure and mutability. Might be worth revisiting in the future
=> [Cider2] Continuous assigns + `with`

fud2/fud-core/src/run.rs
This solves a confusing problem, encountered by both @sgpthomas and @EclecticGriffin in short order, where using fud2 in "stdout mode" (i.e., without `-o`) would suppress errors from the underlying commands by default (i.e., unless you *also* remember to use `-v`). We don't want Ninja printing stuff to stdout, but we also don't like hiding the error messages, so a sensible solution is to just unconditionally make Ninja's progress messages go to stderr. Seems reasonable to me, semantically: all of fud2's output other than the actual content of a "stdout mode" output should go to stderr.
To be super clear about it, there are 4 conditions that matter. Here are sample commands for each:
* Success, file-output mode. Example: `cat anything.futil | fud2 --from calyx --to verilog -o /dev/null`
* …
=> [fud2] Always send Ninja's stdout to our stderr

fud2/fud-core/src/cli.rs, fud2/fud-core/src/run.rs
In #2058, I made fud2 clean up the `.fud2` temporary directory even when Ninja exited with an error. Unfortunately, @nathanielnrn noticed that this doesn't cover other possible errors, such as when launching the Ninja process fails altogether: https://github.com/calyxir/calyx/pull/2058#issuecomment-2136078085
Rather than patching one error at a time, this uses `Drop` to be sure we do this when any error occurs. It also means it will get deleted even when we panic, which is *definitely* overkill, but I guess it's not a big deal.
Unsurprisingly, this is a case where @EclecticGriffin was right all along… they originally suggested the `Drop` method, and I thought that was probably overkill, but they were definitely right after all.
This may also be relevant to @ethanuppal and his efforts in …
=> [fud2] Even more confidently delete the build directory, even when more kinds of errors occur

fud2/fud-core/src/run.rs
A simple patch to fix use with our snapshot testing tools. Opted to forward the verbose flag as well for maximum verbosity.
=> [Fud2] Forward the verbose flag to ninja and otherwise use the quiet flag

fud2/fud-core/Cargo.toml, fud2/fud-core/src/script/plugin.rs
Very minor fix: #2078 added plugins, controlled by a `plugins` key in `fud2.toml`. However, it inadvertently made this option required, i.e., fud2 would crash if this option was not present. Now it's optional! So we just silently proceed with no plugins if none are configured.
Just tagging @sgpthomas for visibility, but I'll auto-merge this one.
=> [fud2] Make plugins optional

fud/fud/errors.py
The multiple paths error displays an old link that leads to a 404, so I fixed it! Thanks @KabirSamsi for spotting this :)
=> [fud] Fix multiple paths error doc link

docs/lang/memories-by-reference.md
Because of a restructuring of the `calyx-py` directory, a link from the docs was looking valid from an mdbook point of view but was actually getting a 404 inside of Github. This PR fixes that.
=> Docs: Fix a link to Python source code

docs/frontends/queues.md
https://github.com/calyxir/calyx/pull/2028 implemented a little trick to save modulo-addition logic in FIFOs, but that did not get pushed through to the [docs](https://docs.calyxir.org/frontends/queues.html). This PR adds a quick paragraph to the docs.
=> Docs: Document the wraparound trick in FIFOs

calyx-opt/src/passes/wire_inliner.rs
Now `wire_inliner` more generally looks for ports marked with `@go` and `@done`. This has proved necessary when creating an `axi_seq_mem` (#1733) that has it's `content_en` marked with `@go`  to conform to [primitive memory signatures](https://github.com/calyxir/calyx/blob/main/primitives/memories/seq.futil#L7).
=> Generalize where `wire_inliner` looks for `go` and `done` ports.

fud2/fud-core/src/run.rs
This PR allows one to use `config_constrained_*` methods to ensure that the value passed in via `--set` is constrained to a set of values.
This seems useful for things expected to be `true` or `false` and is used in #2136 
If this goes against the grain of what we hope `fud2` to be, we can close this without merging.
=> [fud2] Add ability to look for a config key that must be associated with a constrained set of values

docs/debug/cider.md, docs/running-calyx/interpreter.md
Closes #2050.
In the [page about the interpreter](https://docs.calyxir.org/running-calyx/interpreter.html#interpreting-via-fud), the docs were not showing people how to register the interpreter as a fud stage. In the [page about the debugger](https://docs.calyxir.org/debug/cider.html#getting-started), the docs were not telling people to build and register the interpreter first. This PR fixes both of these and makes a couple quick clarity changes.
The PR also guides users about the interpreter not supporting the `invoke` command, and explains how to make progress by running the `compile-invoke` pass. This is needed in both pages.
=> Docs: Add fud registration instructions for Interpreter

calyx-py/calyx/builder.py
Consider this small eDSL program
```python
import calyx.builder as cb
def insert_comp(prog):
comp = prog.component("adder")
a = comp.input("a", 32)
comp.control += []
return comp
def insert_main(prog):
main = prog.component("main")
adder = insert_comp(prog)
adder = main.cell("adder", adder)
main.control += [cb.invoke(adder, in_a=10)]
if __name__ == "__main__":
prog = cb.Builder()
insert_main(prog)
prog.program.emit()
```
For examples like these, the eDSL is unable to automatically infer the widths of constant inputs to `invoke`: in this case`10` and `12`. Instead of throwing an error when running `python bad_invoke.py`, it generates the following Calyx code, in which the widths of `a` and `b` are `None`:
```
import "primitives/core.futil";
component main() -> () {
cells {
adder = adder(); …
```
=> Add error handling to width inference for `invoke`

fud2/fud-core/Cargo.toml, fud2/fud-core/src/exec/data.rs, fud2/fud-core/src/exec/driver.rs, fud2/fud-core/src/script/plugin.rs
When fud2 is build in debug mode, include the file where states and operations are defined in the list view. This is useful when you are writing a script and want to figure out where some state is defined.
=> [fud2] Show op/state source

calyx-py/calyx/builder.py, calyx-py/test/walkthrough.expect, tests/frontend/exp/degree-2-unsigned.expect, tests/frontend/exp/degree-4-signed.expect, tests/frontend/exp/degree-4-unsigned.expect, tests/frontend/relay/softmax.expect, yxi/tests/axi/read-compute-write/seq-mem-vec-add.expect, yxi/tests/axi/read-compute-write/seq-vec-add.expect
Small PR that tweaks the names of the group and cells used in `ComponentBuilder.incr` and `ComponentBuilder.decr`.
Previously, eDSL code like this
```
a_incr_2 = comp.incr(a, 2)
a_incr_4 = comp.incr(a, 4)
```
would raise the assertion error `cell 'a_incr' already exists`. Now, we can construct `incr` (resp. `decr`)' groups with the same register and different `val`s without name clashes.
=> Avoid name clashes with `incr` (resp. `decr`) groups using the same register

calyx-py/calyx/builder.py, calyx-py/test/correctness/matrix.py
This PR adds eDSL support for _latching_ memories and later reading directly off those memories, as opposed to loading the memory's latched value to a register and then reading that register. The eDSL extension is straightforward, and there was a nice opportunity to put this to use in our `matrix.py` example. I added some commentary in the `.py` file, but really we could eventually do with a section in the [builder library walkthrough](https://docs.calyxir.org/builder/walkthrough.html).
=> eDSL: support for latching memories

docs/frontends/queues.md
More progress towards #2067!
This PR takes a stab at tweaking `docs/frontends/queues.md` to incorporate additions from PRs #2164 and #2174.
=> Docs, Queues: binary heap

calyx-py/calyx/queue_data_gen.py
This PR fixes a funny little corner case when trying to generate our fancy commands list sans underflow or overflow. 
Given some target number of commands `n`, the special helper inserts `n/2` `push`es and as many `pop`s into a list, while additionally taking care to ensure that no overflows or underflows occur. However, this can cause an issue when `n` is odd: the commands list thus generated ends up with `n-1` elements, while the rest of the infrastructure expects a `n`-length command list. This PR fixes this by padding a `peek` command at the end when needed.
=> Queues: edge case in data-gen when `num_cmds` is odd

runt.toml
It looks like `calyx-py/test/correctness/queues/*.py` was removed from the path of its runt test by  #2177: i.e. the old `fifo`, `pifo`, and `pifo_tree` tests aren't running at CI. Was this intentional? In case it wasn't, I've made a minor fix to `runt.toml`.
=> Re-enable old queue tests

fud2/fud-core/src/exec/driver.rs
This fixes a regression I introduced where I wasn't generate files in the workdir. Thanks @EclecticGriffin for pointing it out on zulip!
=> [fud2] Generate intermediate files in workdir. 

calyx-opt/src/passes/top_down_compile_control.rs, runt.toml, tests/passes/tdcc-duplicate/seq.expect, tests/passes/tdcc-duplicate/seq.futil
@parthsarkar17 The runt test for duplicate FSMs was passing in the incorrect parameter. What probably happened was that it was using an old pass input parameter name that was updated but then the runt command was not updated. 
This is one of the reasons why we should have at least one snapshot test for the FSM optimizations, so things like this are easier to catch (not a big deal at all, but I think it's good practice from now on).
=> Fix test case for duplicate FSM optimization

interp/src/debugger/commands/core.rs, interp/src/debugger/debugger_core.rs, interp/src/debugger/debugging_context/context.rs, interp/src/debugger/mod.rs, interp/src/main.rs
A small patch that makes the new `restart` command preserve the watchpoints, breakpoints, and command history of the debugger rather than fully resetting it.
=> [Cider 2 | Debugger] Preserve debugger info and command history on restart

interp/src/debugger/commands/core.rs, interp/src/debugger/debugger_core.rs
tiny patch to fix some printing and add a (hopefully helpful) message when an invalid command is given 3 times in a row
=> [Cider 2] Fix explain string + add little message on repeated command errors

fud2/fud-core/src/exec/planner.rs
There was a small bug with the planner where it would stop searching when a through op appeared anywhere in the `ops` map. It really should only stop if an op is one edge away from the current state. This worked before because I guess the `ops` map happened to be ordered in such a way where things worked.
Fixes #2209.
=> [fud2] Fix planner so that it doesn't rely on the order operations are defined

interp/src/serialization/data_dump.rs, interp/tests/unit/uninitialized-port-returns-zero.expect
A simple fix to make the error messages better for the data converter. Particularly it should no longer fail by trying to allocate extremely large amounts of memory when given garbage input, which was generally confusing. Also added a few more error types to make failures a little more understandable when they happen. 
I reserved the first 4 bytes for the magic number and used the remaining 4 for the header length. Previously all 8 bytes were for the header length so this does limit the max header size, but if we find ourselves with multiple gigs worth of header information alone things have probably gone wrong already. That said, it wouldn't be hard to extend in the future if the need arises.
=> [Cider2] Add a magic number to the data dump serialization

Cargo.lock, interp/src/flatten/structures/environment/env.rs, interp/src/flatten/structures/indexed_map.rs, interp/src/serialization/data_dump.rs, tools/cider-data-converter/Cargo.toml, tools/cider-data-converter/src/converter.rs, tools/cider-data-converter/src/json_data.rs, tools/cider-data-converter/src/main.rs
Part of #1913.
Closes #2219.
This ended up being a real headache but I think I have things working enough. There are some glaring inefficiencies in the fixed point conversion code but for the time being I am not overly concerned. For the most part I tried to replicate the original `fud` conversion but did deviate when it comes to rounding with the more standard approach (insofar as I understand it). This doesn't yet adjust the `fud2` path to include the rounding flag, that'll need to come later.
=> [Cider2] Fixed point data initialization and serialization

docs/debug/debug.md
Replace some outdated references in the docs to a `futil` executable, which was long ago renamed to `calyx`. Closes #2228, which was a first attempt at this.
=> [docs] Fix some mentions of old `futil` executable

interp/src/flatten/structures/environment/env.rs
Part of #1913. Modifies changes from #2242.
Small tweak to use a hashmap (begrudgingly) for pinned values internally and adds the ability to unpin values.
=> [Cider2] Use map for pins

interp/src/debugger/commands/command_parser.rs, interp/src/debugger/commands/commands.pest, interp/src/debugger/commands/core.rs, interp/src/debugger/debugger_core.rs, interp/src/debugger/debugging_context/context.rs, interp/src/flatten/structures/environment/env.rs, interp/src/flatten/structures/environment/traverser.rs
Part of #1913.
Adds the ability to enable/disable watchpoints. Also corrects some issues with the name traversals and adds better name printing to debugger outputs.
=> [Cider2] Watchpoint fixes

interp/src/flatten/structures/environment/env.rs
=> [Cider] Tweak FFI 

fud2/fud-core/src/exec/driver.rs, fud2/fud-core/src/script/plugin.rs, fud2/src/main.rs, fud2/tests/tests.rs
It does what it says on the tin. The error messages for the parser won't be good, but they are better than rust panics and I think become functional enough.
One interesting thing to note is I chose to print full paths when referencing files. This is because the directory of scripts is often not where `fud2` was run from and pretty unrelated to that dir.
=> [fud2] improve error message for parser errors

fud2/fud-core/src/run.rs, fud2/fud-core/src/script/error.rs, fud2/fud-core/src/script/plugin.rs
Empty ops currently can be created in the new DSL. When exported, this creates broken ninja code. This is an error of the user, not creating the desired target, but this class of error can never create the desired target. Therefore a helpful error was inserted when this happens.
=> [fud2] Make Empty Ops an Error

fud/fud/stages/verilator/stage.py, fud/icarus/tb.sv, fud2/rsrc/tb.sv, fud2/scripts/icarus.rhai, fud2/scripts/verilator.rhai, fud2/src/lib.rs, fud2/tests/snapshots/tests__test@calyx_through_icarus_to_dat.snap, fud2/tests/snapshots/tests__test@calyx_through_icarus_to_vcd.snap, fud2/tests/snapshots/tests__test@calyx_through_verilator_to_dat.snap, fud2/tests/snapshots/tests__test@calyx_through_verilator_to_vcd.snap, fud2/tests/snapshots/tests__test@calyx_verilator_dat.snap, fud2/tests/snapshots/tests__test@calyx_verilator_vcd.snap, fud2/tests/snapshots/tests__test@plan_icarus-refmem.snap, fud2/tests/snapshots/tests__test@plan_icarus.snap, fud2/tests/snapshots/tests__test@plan_verilator-refmem.snap, fud2/tests/snapshots/tests__test@plan_verilator.snap, tests/correctness/systolic/pe/array-1.systolic.jq, tests/correctness/systolic/pe/array-2.systolic.jq, tests/correctness/systolic/pe/array-3.systolic.jq, tests/errors/runtime/multiple-drivers.expect, tools/firrtl/custom_tb_template.sv
This PR updates the name of the top level module in the Verilog testbench (`tb.sv`) to `toplevel` to avoid the Verilator error:
```
tb.sv:1:8: Module cannot be named 'TOP' as conflicts with Verilator top-level internals
```
=> Testbench toplevel module

fud2/scripts/cider.rhai, fud2/tests/snapshots/tests__test@calyx_through_cider_to_dat.snap, fud2/tests/snapshots/tests__test@calyx_to_cider-debug.snap, fud2/tests/snapshots/tests__test@plan_cider.snap, fud2/tests/snapshots/tests__test@plan_debug.snap, interp/src/errors.rs, interp/src/flatten/flat_ir/base.rs, interp/src/flatten/flat_ir/component.rs, interp/src/flatten/primitives/builder.rs, interp/src/flatten/primitives/stateful/memories.rs, interp/src/flatten/structures/context.rs, interp/src/flatten/structures/environment/env.rs, interp/src/serialization/data_dump.rs, interp/tests/runt.toml
Small tweak for cider which modifies the way errors are processed and improves the error message for conflicting assignments to print both assignments and their origin.
Also adds the data converter flags to the `fud2` flow.
=> [Cider] Improve conflicting assignment error message

interp/src/flatten/primitives/stateful/math.rs, interp/src/serialization/data_dump.rs
Corrects a regression introduced in #2281. Adds some better error reporting for the data dumps.
=> [cider] minor bug in fxp mult

docs/lang/memories-by-reference.md
This PR fixes a bug in a comment in a code snippet in a doc that I noticed during @EclecticGriffin's Cider2 talk
=> Fix comment in ref docs

docs/running-calyx/fud2/index.md, fud2/fud-core/src/cli.rs, fud2/fud-core/src/run.rs, fud2/tests/tests.rs
It does what it says on the tin.
=> [fud2] add flag to print commands instead of running them

.gitignore, Cargo.lock, interp/Cargo.toml, interp/src/debugger/debugger_core.rs, interp/src/flatten/flat_ir/component.rs, interp/src/flatten/flat_ir/control/translator.rs, interp/src/flatten/structures/context.rs, interp/src/flatten/structures/environment/env.rs, interp/src/flatten/structures/environment/mod.rs, interp/src/flatten/structures/environment/wave.rs, interp/src/flatten/structures/indexed_map.rs, interp/src/main.rs
This adds an option to generate a wavedump when executing a Calyx program with cider.
FST generation is based on the highly experimental `fst-writer` library. Currently, the FSTs produced work on Surfer but crash GTKWave.
I would love to get this in - mostly as is - after a review by @EclecticGriffin. I will add more features and fix bugs as they show up.
=> Add FST output for cider

frontends/queues/queues/binheap/stable_binheap.py, frontends/queues/queues/strict_or_rr.py, frontends/queues/tests/binheap/stable_binheap_test.py, frontends/queues/tests/complex_tree_test.py, frontends/queues/tests/pifo_tree_test.py, frontends/queues/tests/sdn_test.py
Here's a snippet from [`complex_tree_test.py`](https://github.com/calyxir/calyx/blob/49fbc2a2e5a962b33380a6d7f2c339b841e7bd2f/frontends/queues/tests/complex_tree_test.py)
```python
def build():
"""Top-level function to build the program."""
num_cmds = int(sys.argv[1])
keepgoing = "--keepgoing" in sys.argv
prog = cb.Builder()
fifo_A = fifo.insert_fifo(prog, "fifo_A")
fifo_B = fifo.insert_fifo(prog, "fifo_B")
fifo_C = fifo.insert_fifo(prog, "fifo_C")
fifo_D = fifo.insert_fifo(prog, "fifo_D")
fifo_E = fifo.insert_fifo(prog, "fifo_E")
fifo_F = fifo.insert_fifo(prog, "fifo_F")
fifo_G = fifo.insert_fifo(prog, "fifo_G")
fifo_H = fifo.insert_fifo(prog, "fifo_H")
pifo_strict1 = strict_or_rr.insert_queue(
prog,
"pifo_strict1",
[fifo_A, fifo_B, fifo_C],
[0, 44, 88, 133],
3,
[0, 1, 2],
False,
)
... …
```
=> Queues: remove duplicate components

Cargo.lock, interp/Cargo.toml
This upgrades to the latest fst-writer which produces FST files that (generally) do not crash gtkwave.
Before this change, most FSTs generated by cider would crash GTKWave :cry: .
=> bump fst-writer version

calyx-frontend/src/attribute.rs, calyx-opt/src/passes/cell_share.rs, calyx-opt/src/passes/dead_cell_removal.rs, docs/lang/attributes.md, primitives/compile.futil, tests/passes/cell-share/protected.expect, tests/passes/cell-share/protected.futil, tests/passes/dead-cell-removal-protected.expect, tests/passes/dead-cell-removal-protected.futil
I added a new boolean attribute that indicates which cells (and uses of cells) should be preserved during optimizations. I check for the attribute in the `dead-cell-removal` pass, so the pass doesn't optimize those cells when it would otherwise do so. (@ekiwi and I got to the bottom of the errors I was experiencing yesterday)
The attribute is currently called `@protected`, but if anyone has suggestions about what the attribute should be named that would be helpful!
The test file `tests/passes/dead-cell-removal-protected.futil` differs from `tests/passes/dead-cell-removal.futil` by a single line, where we add `@protected` to unused register `unused_reg`:
```
$ diff tests/passes/dead-cell-removal.futil tests/passes/dead-cell-removal-protected.futil               
30c30 …
```
=> Attribute to retain cells during optimization

Cargo.lock, interp/Cargo.toml
This reduces the size of BitVecValue from 32 bytes to 24 bytes.
=> bump baa to 0.14.0

fud2/scripts/cider.rhai, fud2/tests/snapshots/tests__test@calyx_through_cider_to_dat.snap, fud2/tests/snapshots/tests__test@calyx_to_cider-debug.snap, fud2/tests/snapshots/tests__test@plan_calyx-to-cider.snap, fud2/tests/snapshots/tests__test@plan_cider.snap, fud2/tests/snapshots/tests__test@plan_debug.snap, interp/tests/complex/unsigned-dot-product.futil, interp/tests/control/while.futil, interp/tests/primitives/mem.futil, interp/tests/runt.toml
A quick patch for the `fud2` flow which makes it possible to run without supplying a `sim.data` value which would otherwise block things. This hopefully makes testing small programs more straightforward as it no longer requires generating an empty data file or using direct invocations of the tools.
=> [Cider | Fud2 stage] Make `sim.data` optional for the Cider fud2 flow

fud2/fud-core/src/cli.rs, fud2/fud-core/src/run.rs, runt.toml
Moving all tests in the root `runt.toml` to use `fud2`.
=> `fud2` Migrate main test suite

interp/src/flatten/flat_ir/cell_prototype.rs, interp/src/serialization/data_dump.rs, interp/tests/runt.toml, tools/cider-data-converter/src/converter.rs, tools/cider-data-converter/src/json_data.rs
Somewhere, things still get messed up.
I get:
```
{
"out": [
15.123900413513184,
0.5600000023841858
],
"inp": [
15.123900413513184
]
}
```
But the expected output is:
```
{
"inp": [
15.12
],
"out": [
15.12,
0.56
]
}
```
=> add floating point support to cider

interp/tests/runt.toml
Sorry, I overlooked Rachit's comment on the previous PR.
=> cider: use jq stage

.github/workflows/docs.yml, book.toml, docs/SUMMARY.md, docs/contributors.md, docs/dev/calyx-pass-explorer.md, docs/github.md, docs/install_tools.sh, docs/intro.md, docs/new-pass.md, interp/tests/runt.toml, tools/calyx-pass-explorer/README.md
This PR adds a documentation page for the `calyx-pass-explorer` tool, serving as a gentle introduction to its usage as well as an overview of its code.
- I've added `mdbook-callouts` as a way to get Obsidian-style quote blocks. Specifically, I'm using this for the `[!TIP]` environment. I can remove this if we don't want another dependency.
- I did some unrelated things (to `docs/contributors.md`, `docs/github.md`, and `docs/intro.md`) that I can move into another PR if that would be better.
=> Write docs for `calyx-pass-explorer`

interp/tests/runt.toml, interp/tests/unit/uninitialized-port-returns-zero.expect, tools/cider-data-converter/src/json_data.rs
=> data-converted: always sort keys in output JSON

interp/src/serialization/data_dump.rs, tools/cider-data-converter/src/main.rs
I did some silly hacking late last week that might get us marginally closer to unifying all the data marshaling under a single tool. 
This adds the ability to specify a `--to dat` (or one of the aliases) and an output directory which will generate the hex encoded files that verilator/icarus expect. There are some minor differences with the dat files generated by the python flow. Mainly, the python flow truncates leading zeroes in the encoding while I've elected to retain them in the interest of keeping things simple. Python generates:
```
4B
53
21
5D
1E
5E
2B
B
3C
60
```
while the data-converter generates
```
0000004B
00000053
00000021
0000005D
0000001E
0000005E
0000002B
0000000B
0000003C
00000060
```
This also adds the ability to deserialize this style of data dump but is slightly …
=> [Data Converter] add experimental dat-style serialization

interp/Cargo.toml, interp/src/flatten/primitives/combinational.rs, interp/src/flatten/primitives/macros.rs, interp/src/flatten/primitives/prim_trait.rs, interp/src/flatten/primitives/stateful/math.rs, interp/src/flatten/primitives/stateful/memories.rs, interp/src/flatten/primitives/utils.rs, interp/src/flatten/structures/environment/env.rs, interp/src/flatten/structures/environment/mod.rs, interp/src/flatten/structures/environment/program_counter.rs, interp/src/flatten/structures/indexed_map.rs, interp/src/flatten/structures/thread.rs
Creates a new `BaseSimulator` object that can be used independently of `Simulator`. Also, things are cloneable now. The rationale is we can now write a model checker using cider by cloning cider contexts at forks.
=> [cider2] Make minimally-sized clonable simulator

Cargo.lock, tools/cider-data-converter/Cargo.toml, tools/cider-data-converter/src/dat_parser.rs, tools/cider-data-converter/src/lib.rs, tools/cider-data-converter/src/main.rs
I spent some more time hacking on this instead of spending my time in a more productive way. This does the following:
- switch the `dat` deserializing from custom matching stuff to a proper `nom` parser that accounts for comments and leading `0x` tags.
- `dat` files can now parse values with leading zeroes truncated (though we continue to generate `dat` files with the leading zeroes included)
- Output `dat` files will be generated by default as `MEMNAME.dat` though this can be customized with `-e` flag. I.e. `-e out` will generate `MEMNAME.out`
- Similarly, when reading in a `dat` directory, the tool will look for `MEMNAME.dat` which can be retargeted via `-e` flag.
- The tool will also infer the `--to json` target when given a directory as input
=> [Data converter] Improve the hex parsing & general functionality

docs/compiler.md, docs/dev/calyx-pass-explorer.md
Closes #2344 since I think it's a relative paths issue.
=> [docs] Fix images in docs for `calyx-pass-explorer`

.github/workflows/rust.yml, frontends/queues/README.md, rust-toolchain.toml
What is says on the tin (as discussed on this [slack thread](https://cucapra.slack.com/archives/C06CV424G94/p1727223025447109))
Due to a new [release](https://releases.rs/docs/1.83.0/) for rust, CI catches a few errors (unrelated to this PR). For now, we simply pin to an older version:
- remove toolchain argument for `setup-rust-toolchain@v1` in `rust.yml`
- add `rust-toolchain.toml`
=> Queues: add instructions for converting tests to Calyx

Cargo.lock, calyx-frontend/src/parser.rs, calyx-utils/Cargo.toml, calyx-utils/src/errors.rs, calyx-utils/src/position.rs
Uses interior mutability with a `RwLock` and `lazy_static!`.
=> Fix failing tests on `main` due to new Rust version

fud2/scripts/profiler.rhai, fud2/tests/snapshots/tests__test@plan_profiler.snap
Forgot to remove `par-to-seq` from profiler passes after implementing profiling for parallel programs!!! I'll be more careful in the future.
=> Remove par-to-seq from profiler passes

.github/workflows/docs.yml, .github/workflows/format.yml, .github/workflows/playground.yml, calyx-backend/src/backend_opt.rs, calyx-backend/src/verilog.rs, calyx-ir/src/guard.rs, calyx-ir/src/printer.rs, calyx-opt/src/analysis/domination_analysis/dominator_map.rs, calyx-opt/src/analysis/graph.rs, calyx-opt/src/analysis/graph_coloring.rs, calyx-opt/src/analysis/inference_analysis.rs, calyx-opt/src/analysis/static_tree.rs, calyx-opt/src/analysis/variable_detection.rs, calyx-opt/src/passes/cell_share.rs, calyx-opt/src/passes/collapse_control.rs, calyx-opt/src/passes/group_to_invoke.rs, calyx-opt/src/passes/lower_guards.rs, calyx-opt/src/passes/static_promotion.rs, calyx-opt/src/passes/well_formed.rs, calyx-opt/src/passes_experimental/sync/compile_sync_without_sync_reg.rs, calyx-opt/src/traversal/construct.rs, calyx-utils/src/out_file.rs, calyx-utils/src/pos_string.rs, calyx-utils/src/weight_graph.rs, rust-toolchain.toml, src/cmdline.rs, tools/data-conversion/src/main.rs
Supersedes #2369.
`rust-toolchain.toml` now determines the version of rust used for every aspect of the CI, rather than having it change on its own or be set separately. As it turns out, the version of rust used for the clippy lints was also pinned separately, so I also had to address all those lints. As a result, I had to make minor changes to a bunch of code, the vast majority of which were either docstring indents or places where people manually implemented `ToString` instead of using `Display`. I don't anticipate any of these changes messing with things but if I did break something, do let me know.
Assuming I've done things correctly, it should be the case that the rust version will not change on its own anymore, and we can update the version used by all of Ci by editing the toolchain …
=> [CI] Standardize a single rust toolchain for all of CI

frontends/queues/test_data_gen/gen_test_data.sh
Small edits to `gen_test_data.sh` to generate `.data` files with argument-specified lengths of commands, and a specified output directory. If no arguments are provided, the size and the output directory are set to the default (20000 and `<SCRIPT_DIR>/../tests`). It's a bit hacky, but since I only need it for profiler debugging purposes, I hope it's ok?
=> Generate queue `.data` files according to custom command size

docs/running-calyx/fud2/index.md
The existing instructions did not work to add `fud2` to my path (locally on macOS). FWICT `cargo install --path fud2` did. Maybe we also want to get rid of the previous instructions? Not sure if they are still valid.
=> Add alternative fud2 installation instructions

calyx-py/calyx/builder.py
Another part of #2267 that makes sense to live on it's own. Sorry for so many small PRs! But whittling things down like this is helping me better remember where everything stands
=> Remove redundant output_with_attributes from python builder

calyx-backend/src/xilinx/xml.rs, docs/running-calyx/fud/axi-gen.md, docs/running-calyx/fud/xilinx.md, yxi/axi-calyx/axi-combined-calyx.futil, yxi/xml/xml_generator.py
AMD decided to bork the old links to a bunch of useful docs, this updates that.
Just comment changes so going to auto merge
=> Update xilinx doc links

cider/src/debugger/commands/core.rs
Tiny patch to replace `OnceLock` since `LazyLock` works in this case and is slightly simpler
=> [Cider] replace `OnceLock` with `LazyLock`

fud/fud/stages/vivado/extract.py
Closes #2288
I've checked that this grabs the correct values. Say our `main_utilization_placed.rpt` file had the following BRAM table
(not a real utilization file, I changed the highlighted entry from 0 to 9 to make sure I'm grabbing the correct value)
Running `fud e --from synth-files --to resource-estimate report` yields the correct BRAM count of `9`:
```
{
"lut": 169,
"dsp": 0,
"brams": 9,
"registers": 60,
"muxes": 30,
"clb_registers": 210,
"carry8": 10,
"f7_muxes": 0,
"f8_muxes": 0,
"f9_muxes": 0,
"clb": 389,
"meet_timing": 1,
"worst_slack": 4.758,
"period": 7.0,
"frequency": 142.857,
"uram": -1,
"cell_lut1": 5,
"cell_lut2": 110,
"cell_lut3": 38,
"cell_lut4": 17,
"cell_lut5": 18,
"cell_lut6": 49,
"cell_fdre": 210
}
```
=> Add BRAM numbers to resource estimate executive summary

calyx-frontend/src/source_info.rs, cider/src/debugger/debugger_core.rs, cider/src/flatten/flat_ir/component.rs, cider/src/flatten/flat_ir/control/structures.rs, cider/src/flatten/flat_ir/control/translator.rs, cider/src/flatten/structures/context.rs, cider/src/flatten/structures/environment/env.rs, cider/src/flatten/structures/environment/program_counter.rs, cider/src/flatten/structures/printer.rs
A quick and dirty integration of the newer sourceinfo into Cider such that requesting the program counter will display the source filename & line when available, similar to how it used to work with the embedded metadata lines.
=> [Cider] Barebones integration of the `SourceInfoTable` 

Cargo.lock, cider/Cargo.toml, cider/src/debugger/io_utils.rs, cider/tests/debugger/source_info.expect, cider/tests/debugger/source_info.futil, cider/tests/debugger/source_info.futil.commands, cider/tests/runt.toml, fud2/scripts/cider.rhai, fud2/tests/snapshots/tests__test@calyx_through_cider_to_dat.snap, fud2/tests/snapshots/tests__test@calyx_to_cider-debug.snap, fud2/tests/snapshots/tests__test@plan_cider.snap, fud2/tests/snapshots/tests__test@plan_debug.snap
A quick PR that modifies the `fud2` execution of the debugger and some of the debugger internals to make it possible to run tests on its behavior. Using this, it adds a quick test for the display of the new source info.
=> [Cider] Add test for debugger use of source info

Cargo.lock, cider/Cargo.toml, cider/idx/src/indexed_map.rs, cider/idx/src/sparse_map.rs, cider/src/configuration.rs, cider/src/debugger/commands/core.rs, cider/src/debugger/debugger_core.rs, cider/src/debugger/debugging_context/context.rs, cider/src/debugger/macros.rs, cider/src/errors.rs, cider/src/flatten/flat_ir/base.rs, cider/src/flatten/flat_ir/component.rs, cider/src/flatten/flat_ir/control/translator.rs, cider/src/flatten/primitives/stateful/memories.rs, cider/src/flatten/structures/context.rs, cider/src/flatten/structures/environment/clock.rs, cider/src/flatten/structures/environment/env.rs, cider/src/flatten/structures/environment/program_counter.rs, cider/src/flatten/structures/printer.rs, cider/src/flatten/text_utils.rs, cider/src/main.rs, cider/src/serialization/formatting.rs, cider/tests/data-race/conflict.expect, cider/tests/data-race/continuous-race.expect, cider/tests/data-race/guard-conflict.expect, cider/tests/data-race/par-conflict-cmem.expect, cider/tests/data-race/par-conflict.expect, cider/tests/data-race/strange_mult.expect, cider/tests/data-race/write-write.expect, cider/tests/data-race/write-write.futil
A glob of stuff that improves data race errors by printing out the reads and writes which caused them. There's also some futzing around color printing and a new flag that forces it to be enabled, since now running through `fud2` won't have colors by default
=> [Cider] Improve data race errors

calyx/opt/src/default_passes.rs, fud2/scripts/profiler.rhai, fud2/tests/snapshots/tests__test@plan_calyx-py-profiler.snap, fud2/tests/snapshots/tests__test@plan_profiler.snap
The pass order used for profiling (both in the `-p profiler` pass and set in fud2) was buggy since validation of the original program would happen _after_ the profiler-specific compiler passes. When profiling, we compile static groups before instrumentation (because we can't directly instrument static groups), so validation fails when an (originally static) group uses a static cell, such as `pipelined_mult`.
Thanks @pedropontesgarcia for trying out the profiler and letting me know about this!
=> [Profiler] Fix compiler pass order for profiling

cider/src/debugger/commands/command_parser.rs, cider/src/debugger/commands/commands.pest, cider/src/debugger/commands/core.rs, cider/src/debugger/debugger_core.rs, cider/tests/debugger/infinite_group.expect, cider/tests/debugger/infinite_group.futil, cider/tests/debugger/infinite_group.futil.commands
Inspired by some attempts to debug an infinite loop or group running longer than expected, this PR adds an optional bound `n` to the `step-over` command. When present, the debugger will return control to the user after `n` cycles if the group is still running. If not provided, the behavior is the same as before, where it will continue to run until the group exits. In the case of non-terminating groups, this leads to an indefinite hang.
=> [Cider] Extend `step-over` for easier debugging of infinite/long groups

cider/idx/src/index_trait.rs, cider/src/debugger/commands/core.rs, cider/src/debugger/debugger_core.rs, cider/src/flatten/flat_ir/control/translator.rs, cider/src/flatten/flat_ir/flatten_trait.rs, cider/src/flatten/flat_ir/wires/guards.rs, cider/src/flatten/structures/environment/env.rs, cider/src/flatten/structures/printer.rs, cider/src/flatten/text_utils.rs
Small PR which reimplements the display command which was left behind during the overhaul. Rather than dump the ports for all cells in the main components, as was the previous behavior, I've opted to make it only dump the ports for cells which are in currently executing groups. A limitation of this behavior is that groups which are on their last cycle, i.e. their done ports are high, will not be counted as active.
Also, I decided to hash cons the guards finally, though I am not sure why I decided to do this now.
=> [Cider] Reimplement the display command

calyx/opt/src/passes/cell_share.rs, tests/passes/cell-share/emit-share-map.expect, tests/passes/cell-share/emit-share-map.futil
This PR adds the `emit-share-map` option to `cell-share` that emits the mapping between old and new cells in JSON format. The motivation for this is that I realized that the profiler sometimes needs to know when/how cells are shared. As always, please let me know if there's anything I should change here!
The test `tests/passes/cell-share/emit-share-map.futil` contains three cells (`id_1`, `id_2`, `id_3`) of component `identity` that can be shared. When running `cargo run -- tests/passes/cell-share/emit-share-map.futil -p cell-share -p cell-share:emit-share-map:map.json`, the following is written to `map.json`:
```
{
"identity": [],
"main": [
{
"original": "id_3",
"new": "id_1",
"cell_type": "identity"
},
{
"original": "id_2",
"new": "id_1",
"cell_type": "identity"
}
]
}
```
This indicates …
=> [cell-share] Option for emitting shared cells in JSON format

primitives/float/addFN.futil, primitives/float/compareFN.futil, primitives/float/divSqrtFN.futil, primitives/float/mulFN.futil
This patch adds the `interval` attribute to all the pseudo-pipelined floating point library operations with value equals to 4. We also add `write_together` to the `go` signal.
=> [Floating Point] Add `write_together` and `interval` attribute to the floating point library ops

calyx-py/calyx/numeric_types.py, tests/correctness/hardfloat/compareFN.futil.data
Two's complement to positive decimal representation should fall into [0, (2^(width-1)) - 1], instead of [0, (2^(width-1))].
=> [BitNum] Correct the upper bound when converting two's complement to decimal negative values

calyx/backend/src/verilog.rs, calyx/stdlib/src/primitives.rs, primitives/float/get_hardfloat.sh
We should not set the directory of the Berkeley Hardfloat library to be relative to the current working directory because it will result in path error when using `fud2`, which creates a fresh directory for `ninja`.
=> [Floating Point] Hardfloat path should not be relative to the current working directory

cider/src/flatten/flat_ir/component.rs, cider/src/flatten/structures/context.rs, cider/src/flatten/structures/environment/env.rs
Minor set of changes to fix some code that was broken by #2456, namely the ability to search for assignments in groups that do not appear in the control tree.
=> [Cider] Structural enable fixes

calyx/opt/src/passes/top_down_compile_control.rs, tools/profiler/profiler-process/classes.py, tools/profiler/profiler-process/main.py, tools/profiler/profiler-process/visuals/stats.py, tools/profiler/profiler-process/visuals/timeline.py
The VCD-processing scripts now produce statistics about groups, including the min/max/average number of cycles the group was active for on each enable. If `min` == `max`, then the group is a candidate to be converted to `static`.
I also brought back changes to TDCC that output par parent-child info that was removed.
=> [Profiler] Producing group statistics

calyx/opt/src/default_passes.rs, fud2/scripts/profiler.rhai, fud2/tests/snapshots/tests__test@plan_calyx-py-profiler.snap, fud2/tests/snapshots/tests__test@plan_profiler.snap
I found differences in cycle counts when running @jiahanxie353 's ffnn program, for which the root cause was `group2seq` making programs _slower_. A more detailed explanation is in Issue #2470 !
=> Temporarily removing `group2seq` from profiler pipeline

fud/fud/config.py, fud/fud/main.py, fud/fud/stages/__init__.py, fud/fud/stages/remote_context.py, fud/fud/stages/vivado/extract.py, fud/fud/stages/xilinx/execution.py, fud/icarus/icarus.py
This small PR resolves the annoying deprecation warnings of the `logger` library:
```python
DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
```
=> Resolve logger warnings

fud2/scripts/vcd_json.rhai, fud2/tests/snapshots/tests__list_ops.snap, fud2/tests/snapshots/tests__test@plan_vcd_json.snap
Turned out to be a pretty simple tool invocation. You can now use `--through vcd_json` as in original `fud`
=> [Fud2] Add the `vcd_json` op for `fud2`

Cargo.lock, fud2/fud-core/Cargo.toml, fud2/fud-core/src/lib.rs, fud2/fud-core/src/run.rs, fud2/fud-core/src/uninterrupt.rs
Fixes #2154, which is about leaving the `.fud2` directory behind when you interrupt execution with ^C.
The idea is to suppress the default behavior of SIGINT *for the fud2 process only*. SIGINT still goes to the child process, i.e., to Ninja. This way, when you type ^C when running fud2, it kills the underlying Ninja process as you expect, but fud2 still gets a chance to clean up afterward---notably, by deleting the `.fud2` working directory.
Interestingly, the solution here is to register a no-op handler for SIGINT. This is distinct from using SIG_IGN, which ignores the signal for the entire process group (not what we want: it would make it impossible to stop Ninja too!).
This seems to work here; interrupting with ^C looks like this:
```
$ fud2 --from ntt …
```
=> fud2: Suppress SIGINT during Ninja execution

fud2/fud-core/src/cli.rs
a tiny typo fix. 
It seems like `argh` does not provide any way to access its generated help message.
=> [fud2] Fix typo

fud2/src/cli_pyenv.rs
make `fud2 env activate` print out a command which can be `eval`ed to activate the venv, or just copied and run separately and reference this in the `init` printout
=> [fud 2] tweak `fud2 env activate`

tools/report-parsing/pyproject.toml
Tiny fix to prevent `fud2 env init` from exploding because it can't find the license file
=> [Fud2] comment out the license file so the command doesn't break

calyx/opt/src/passes_experimental/metadata_table_gen.rs, tests/passes/metadata-table-gen-non-empty.expect, tests/passes/metadata-table-gen.expect
The `metadata-table-gen` pass previously didn't create position attributes for components, but this PR adds those in!
=> [metadata-table-gen] Add sourceloc info for components

Cargo.lock, web/rust/Cargo.toml, web/rust/src/lib.rs
We've been getting a "future incompatibility" warning from this package for a while but it turns out this would be a blocker if we ever wanted to switch to rust 1.88 (the one with let chains). I opted to bump it to the most recent version, which it turns out requests the use of `serde_wasm_bindgen` as the `to_serde` method is now deprecated. The path to resolution seems to be using `serde_wasm_bindgen::from_value` in place of `to_serde`. I had to throw in a clone but given that the jsvalues are basically just a newtype this should be a trivial cost.
Hopefully this just works? I don't actually know how to test the playground, so I'm hoping one of y'all has insight.
=> [misc] bump wasm bindgen version

docs/frontends/dahlia.md, docs/frontends/mrxl.md, docs/frontends/ntt.md, docs/intro.md, docs/lang/data-format.md, docs/lang/memories-by-reference.md, docs/lang/multi-component.md, docs/tutorial/frontend-tut.md, docs/tutorial/language-tut.md
Here's a quick attempt to convert all the low-hanging fruit I could find in the docs to refer to fud2 instead of fud. I haven't done anything about the actual fud docs themselves, the "experimental" label, or anything like that.
Most of the changes are pretty mechanical. The only substantial bit of new writing is in the "getting started" guide, where I added a compressed overview of how to install fud2 (which is of course already explained in more detail on the main fud2 docs page).
I'm sure there's plenty more to do here, but I thought I'd just get the ball rolling!
=> [docs] First cut at recommending fud2 throughout

fud2/scripts/synth-verilog-to-report.rhai, fud2/tests/snapshots/tests__test@plan_area-report-to-flamegraph.snap, fud2/tests/snapshots/tests__test@plan_synth-verilog-to-area-report.snap, fud2/tests/snapshots/tests__test@plan_synth-verilog-to-hierarchy-json.snap, fud2/tests/snapshots/tests__test@plan_synth-verilog-to-timing-report.snap, fud2/tests/snapshots/tests__test@plan_synth-verilog-to-util-json.snap, fud2/tests/snapshots/tests__test@plan_synth-verilog-to-util-report.snap
Split setup functions to remove unnecessary dependency on Flamegraph config var for several fud2 synthesis ops.
=> [`fud2`] Removed unnecessary dependency on Flamegraph config var

.github/workflows/rust.yml, Dockerfile, calyx-py/calyx/py_ast.py
Following up on #2534, we apparently now _need_ to use uv to do this install to take advantage of the workspace (i.e., fud's dependency on calyx-py). So I have switched the Dockerfile to use uv instead of flit everywhere!
I am hoping this resolves the CI failure showing up in #2530.
=> Dockerfile: Switch from flit to uv

fud2/fud-core/src/cli.rs, fud2/fud-core/src/exec/data.rs, fud2/fud-core/src/exec/driver.rs, fud2/tests/tests.rs
Closes #2206 
A small change to the could not find path error message. It now lists the set of sources and the set of destinations that it failed to find a path for. Probably should do something better for the multi-input version but I don't know enough about that to properly speculate. Only other thing of note is that I changed the plan function to take a reference to the request rather than owning it which results in one clone of a pathbuf which I think is acceptable.
Now when running a nonsense command, such as going from dat to cider-debug we get the following error message:
```
Error: could not find path from {dat} to {cider-debug}
```
=> [Fud2] Tweak error message to list states

fud2/fud-core/src/cli.rs, fud2/fud-core/src/run.rs
Closes #2526 
Adds a flag that if the directory used by fud2 already exists (either `--keep` or `--dir`) and the `build.ninja` file exists then it will force ninja to cleanup all the build artifacts before running again. This makes it as though the prior build did not happen.
=> [fud2] add a --force-rebuild flag

docs/SUMMARY.md, docs/lang/attributes.md, docs/tools/source-locations.md
Some documentation about the `@pos` set attribute and the `sourceinfo` metadata table (from #2396 )! Please let me know of any thoughts or changes.
=> [Docs] Documentation about Source Location Metadata

calyx/frontend/src/source_info.rs, cider/src/debugger/debugger_core.rs, cider/src/flatten/text_utils.rs, cider/tests/debugger/file1, cider/tests/debugger/file2, cider/tests/debugger/if.expect, cider/tests/debugger/infinite_group.expect, cider/tests/debugger/interactions.expect, cider/tests/debugger/pow.expect, cider/tests/debugger/source_info.expect, cider/tests/debugger/source_info.futil
Small set of changes to allow cider to print the source lines indicated by the sourcemap when they are available during execution. If unable to find the file it will print an error message and then continue execution. Currently this error message is not suppressed by the quiet setting. The correct thing to do would probably be to display it through logging as a warning to allow it to be suppressed, but I leave that for another time
=> [Cider] Proper source printing
